// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: grover.proto

package groverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointType int32

const (
	EndpointType_ENDPOINT_TYPE_UNSPECIFIED EndpointType = 0 // default value, must be 0
	EndpointType_HTTP                      EndpointType = 1
	EndpointType_LOCAL_FS                  EndpointType = 2
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "ENDPOINT_TYPE_UNSPECIFIED",
		1: "HTTP",
		2: "LOCAL_FS",
	}
	EndpointType_value = map[string]int32{
		"ENDPOINT_TYPE_UNSPECIFIED": 0,
		"HTTP":                      1,
		"LOCAL_FS":                  2,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_grover_proto_enumTypes[0].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_grover_proto_enumTypes[0]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{0}
}

type CredentialType int32

const (
	CredentialType_CREDENTIAL_TYPE_UNSPECIFIED CredentialType = 0
	CredentialType_SSH_CREDENTIAL_TYPE         CredentialType = 1
	CredentialType_BASIC_CREDENTIAL_TYPE       CredentialType = 2
)

// Enum value maps for CredentialType.
var (
	CredentialType_name = map[int32]string{
		0: "CREDENTIAL_TYPE_UNSPECIFIED",
		1: "SSH_CREDENTIAL_TYPE",
		2: "BASIC_CREDENTIAL_TYPE",
	}
	CredentialType_value = map[string]int32{
		"CREDENTIAL_TYPE_UNSPECIFIED": 0,
		"SSH_CREDENTIAL_TYPE":         1,
		"BASIC_CREDENTIAL_TYPE":       2,
	}
)

func (x CredentialType) Enum() *CredentialType {
	p := new(CredentialType)
	*p = x
	return p
}

func (x CredentialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialType) Descriptor() protoreflect.EnumDescriptor {
	return file_grover_proto_enumTypes[1].Descriptor()
}

func (CredentialType) Type() protoreflect.EnumType {
	return &file_grover_proto_enumTypes[1]
}

func (x CredentialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialType.Descriptor instead.
func (CredentialType) EnumDescriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{1}
}

type CredentialRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*CredentialRef_CredentialUuid
	//	*CredentialRef_CredentialName
	Ref           isCredentialRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRef) Reset() {
	*x = CredentialRef{}
	mi := &file_grover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRef) ProtoMessage() {}

func (x *CredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRef.ProtoReflect.Descriptor instead.
func (*CredentialRef) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialRef) GetRef() isCredentialRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *CredentialRef) GetCredentialUuid() string {
	if x != nil {
		if x, ok := x.Ref.(*CredentialRef_CredentialUuid); ok {
			return x.CredentialUuid
		}
	}
	return ""
}

func (x *CredentialRef) GetCredentialName() string {
	if x != nil {
		if x, ok := x.Ref.(*CredentialRef_CredentialName); ok {
			return x.CredentialName
		}
	}
	return ""
}

type isCredentialRef_Ref interface {
	isCredentialRef_Ref()
}

type CredentialRef_CredentialUuid struct {
	CredentialUuid string `protobuf:"bytes,1,opt,name=credential_uuid,json=credentialUuid,proto3,oneof"`
}

type CredentialRef_CredentialName struct {
	CredentialName string `protobuf:"bytes,2,opt,name=credential_name,json=credentialName,proto3,oneof"`
}

func (*CredentialRef_CredentialUuid) isCredentialRef_Ref() {}

func (*CredentialRef_CredentialName) isCredentialRef_Ref() {}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.v1.EndpointType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CredentialRef *CredentialRef         `protobuf:"bytes,3,opt,name=CredentialRef,proto3" json:"CredentialRef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_grover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{1}
}

func (x *MkdirRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_grover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{2}
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.v1.EndpointType" json:"type,omitempty"`
	OldPath       string                 `protobuf:"bytes,2,opt,name=oldPath,proto3" json:"oldPath,omitempty"`
	NewPath       string                 `protobuf:"bytes,3,opt,name=newPath,proto3" json:"newPath,omitempty"`
	CredentialRef *CredentialRef         `protobuf:"bytes,4,opt,name=credentialRef,proto3" json:"credentialRef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_grover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{3}
}

func (x *RenameRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *RenameRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_grover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{4}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_grover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.v1.EndpointType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CredentialRef *CredentialRef         `protobuf:"bytes,3,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"` // optional for localfs; required for some remote backends
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_grover_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_grover_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type RemoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.v1.EndpointType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CredentialRef *CredentialRef         `protobuf:"bytes,3,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"` // may be required depending on backend
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_grover_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFileRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *RemoveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveFileRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type RemoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileResponse) Reset() {
	*x = RemoveFileResponse{}
	mi := &file_grover_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResponse) ProtoMessage() {}

func (x *RemoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Full credential (includes secrets by design).
type Credential struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialUuid string                 `protobuf:"bytes,1,opt,name=credential_uuid,json=credentialUuid,proto3" json:"credential_uuid,omitempty"`
	CredentialName string                 `protobuf:"bytes,2,opt,name=credential_name,json=credentialName,proto3" json:"credential_name,omitempty"`
	Type           CredentialType         `protobuf:"varint,3,opt,name=type,proto3,enum=grover.v1.CredentialType" json:"type,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*Credential_Basic
	//	*Credential_Ssh
	Details       isCredential_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_grover_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{10}
}

func (x *Credential) GetCredentialUuid() string {
	if x != nil {
		return x.CredentialUuid
	}
	return ""
}

func (x *Credential) GetCredentialName() string {
	if x != nil {
		return x.CredentialName
	}
	return ""
}

func (x *Credential) GetType() CredentialType {
	if x != nil {
		return x.Type
	}
	return CredentialType_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *Credential) GetDetails() isCredential_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Credential) GetBasic() *BasicDetails {
	if x != nil {
		if x, ok := x.Details.(*Credential_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *Credential) GetSsh() *SshDetails {
	if x != nil {
		if x, ok := x.Details.(*Credential_Ssh); ok {
			return x.Ssh
		}
	}
	return nil
}

type isCredential_Details interface {
	isCredential_Details()
}

type Credential_Basic struct {
	Basic *BasicDetails `protobuf:"bytes,10,opt,name=basic,proto3,oneof"` // for BASIC
}

type Credential_Ssh struct {
	Ssh *SshDetails `protobuf:"bytes,11,opt,name=ssh,proto3,oneof"` // for SSH
}

func (*Credential_Basic) isCredential_Details() {}

func (*Credential_Ssh) isCredential_Details() {}

type BasicDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // secret
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicDetails) Reset() {
	*x = BasicDetails{}
	mi := &file_grover_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicDetails) ProtoMessage() {}

func (x *BasicDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicDetails.ProtoReflect.Descriptor instead.
func (*BasicDetails) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{11}
}

func (x *BasicDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BasicDetails) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SshDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // secret
	UseAgent      bool                   `protobuf:"varint,6,opt,name=use_agent,json=useAgent,proto3" json:"use_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshDetails) Reset() {
	*x = SshDetails{}
	mi := &file_grover_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshDetails) ProtoMessage() {}

func (x *SshDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshDetails.ProtoReflect.Descriptor instead.
func (*SshDetails) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{12}
}

func (x *SshDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SshDetails) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SshDetails) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SshDetails) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SshDetails) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SshDetails) GetUseAgent() bool {
	if x != nil {
		return x.UseAgent
	}
	return false
}

type CreateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialRequest) Reset() {
	*x = CreateCredentialRequest{}
	mi := &file_grover_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialRequest) ProtoMessage() {}

func (x *CreateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCredentialRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type CreateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialResponse) Reset() {
	*x = CreateCredentialResponse{}
	mi := &file_grover_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialResponse) ProtoMessage() {}

func (x *CreateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialResponse.ProtoReflect.Descriptor instead.
func (*CreateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{14}
}

type GetCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *CredentialRef         `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_grover_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{15}
}

func (x *GetCredentialRequest) GetRef() *CredentialRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_grover_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{16}
}

func (x *GetCredentialResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type ListCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CredentialType         `protobuf:"varint,1,opt,name=type,proto3,enum=grover.v1.CredentialType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsRequest) Reset() {
	*x = ListCredentialsRequest{}
	mi := &file_grover_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsRequest) ProtoMessage() {}

func (x *ListCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{17}
}

func (x *ListCredentialsRequest) GetType() CredentialType {
	if x != nil {
		return x.Type
	}
	return CredentialType_CREDENTIAL_TYPE_UNSPECIFIED
}

type ListCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*Credential          `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsResponse) Reset() {
	*x = ListCredentialsResponse{}
	mi := &file_grover_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsResponse) ProtoMessage() {}

func (x *ListCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{18}
}

func (x *ListCredentialsResponse) GetCredentials() []*Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ListCredentialsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *CredentialRef         `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_grover_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCredentialRequest) GetRef() *CredentialRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_grover_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{20}
}

var File_grover_proto protoreflect.FileDescriptor

const file_grover_proto_rawDesc = "" +
	"\n" +
	"\fgrover.proto\x12\tgrover.v1\"l\n" +
	"\rCredentialRef\x12)\n" +
	"\x0fcredential_uuid\x18\x01 \x01(\tH\x00R\x0ecredentialUuid\x12)\n" +
	"\x0fcredential_name\x18\x02 \x01(\tH\x00R\x0ecredentialNameB\x05\n" +
	"\x03ref\"\x8f\x01\n" +
	"\fMkdirRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.grover.v1.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12>\n" +
	"\rCredentialRef\x18\x03 \x01(\v2\x18.grover.v1.CredentialRefR\rCredentialRef\"\x0f\n" +
	"\rMkdirResponse\"\xb0\x01\n" +
	"\rRenameRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.grover.v1.EndpointTypeR\x04type\x12\x18\n" +
	"\aoldPath\x18\x02 \x01(\tR\aoldPath\x12\x18\n" +
	"\anewPath\x18\x03 \x01(\tR\anewPath\x12>\n" +
	"\rcredentialRef\x18\x04 \x01(\v2\x18.grover.v1.CredentialRefR\rcredentialRef\"\x10\n" +
	"\x0eRenameResponse\"B\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\x94\x01\n" +
	"\x10ListFilesRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.grover.v1.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12?\n" +
	"\x0ecredential_ref\x18\x03 \x01(\v2\x18.grover.v1.CredentialRefR\rcredentialRef\">\n" +
	"\x11ListFilesResponse\x12)\n" +
	"\x05files\x18\x01 \x03(\v2\x13.grover.v1.FileInfoR\x05files\"\x95\x01\n" +
	"\x11RemoveFileRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.grover.v1.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12?\n" +
	"\x0ecredential_ref\x18\x03 \x01(\v2\x18.grover.v1.CredentialRefR\rcredentialRef\".\n" +
	"\x12RemoveFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf4\x01\n" +
	"\n" +
	"Credential\x12'\n" +
	"\x0fcredential_uuid\x18\x01 \x01(\tR\x0ecredentialUuid\x12'\n" +
	"\x0fcredential_name\x18\x02 \x01(\tR\x0ecredentialName\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.grover.v1.CredentialTypeR\x04type\x12/\n" +
	"\x05basic\x18\n" +
	" \x01(\v2\x17.grover.v1.BasicDetailsH\x00R\x05basic\x12)\n" +
	"\x03ssh\x18\v \x01(\v2\x15.grover.v1.SshDetailsH\x00R\x03sshB\t\n" +
	"\adetails\"X\n" +
	"\fBasicDetails\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xad\x01\n" +
	"\n" +
	"SshDetails\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\x12\x1b\n" +
	"\tuse_agent\x18\x06 \x01(\bR\buseAgent\"P\n" +
	"\x17CreateCredentialRequest\x125\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x15.grover.v1.CredentialR\n" +
	"credential\"\x1a\n" +
	"\x18CreateCredentialResponse\"B\n" +
	"\x14GetCredentialRequest\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.grover.v1.CredentialRefR\x03ref\"N\n" +
	"\x15GetCredentialResponse\x125\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x15.grover.v1.CredentialR\n" +
	"credential\"G\n" +
	"\x16ListCredentialsRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.grover.v1.CredentialTypeR\x04type\"z\n" +
	"\x17ListCredentialsResponse\x127\n" +
	"\vcredentials\x18\x01 \x03(\v2\x15.grover.v1.CredentialR\vcredentials\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"E\n" +
	"\x17DeleteCredentialRequest\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.grover.v1.CredentialRefR\x03ref\"\x1a\n" +
	"\x18DeleteCredentialResponse*E\n" +
	"\fEndpointType\x12\x1d\n" +
	"\x19ENDPOINT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\f\n" +
	"\bLOCAL_FS\x10\x02*e\n" +
	"\x0eCredentialType\x12\x1f\n" +
	"\x1bCREDENTIAL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SSH_CREDENTIAL_TYPE\x10\x01\x12\x19\n" +
	"\x15BASIC_CREDENTIAL_TYPE\x10\x022\x92\x02\n" +
	"\vFileService\x12A\n" +
	"\x04List\x12\x1b.grover.v1.ListFilesRequest\x1a\x1c.grover.v1.ListFilesResponse\x12E\n" +
	"\x06Remove\x12\x1c.grover.v1.RemoveFileRequest\x1a\x1d.grover.v1.RemoveFileResponse\x12:\n" +
	"\x05Mkdir\x12\x17.grover.v1.MkdirRequest\x1a\x18.grover.v1.MkdirResponse\x12=\n" +
	"\x06Rename\x12\x18.grover.v1.RenameRequest\x1a\x19.grover.v1.RenameResponse2\xd2\x02\n" +
	"\x11CredentialService\x12Q\n" +
	"\x06Create\x12\".grover.v1.CreateCredentialRequest\x1a#.grover.v1.CreateCredentialResponse\x12H\n" +
	"\x03Get\x12\x1f.grover.v1.GetCredentialRequest\x1a .grover.v1.GetCredentialResponse\x12M\n" +
	"\x04List\x12!.grover.v1.ListCredentialsRequest\x1a\".grover.v1.ListCredentialsResponse\x12Q\n" +
	"\x06Delete\x12\".grover.v1.DeleteCredentialRequest\x1a#.grover.v1.DeleteCredentialResponseB<Z:github.com/jgoldverg/grover/pkg/groverpb/groverv1;groverv1b\x06proto3"

var (
	file_grover_proto_rawDescOnce sync.Once
	file_grover_proto_rawDescData []byte
)

func file_grover_proto_rawDescGZIP() []byte {
	file_grover_proto_rawDescOnce.Do(func() {
		file_grover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grover_proto_rawDesc), len(file_grover_proto_rawDesc)))
	})
	return file_grover_proto_rawDescData
}

var file_grover_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grover_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_grover_proto_goTypes = []any{
	(EndpointType)(0),                // 0: grover.v1.EndpointType
	(CredentialType)(0),              // 1: grover.v1.CredentialType
	(*CredentialRef)(nil),            // 2: grover.v1.CredentialRef
	(*MkdirRequest)(nil),             // 3: grover.v1.MkdirRequest
	(*MkdirResponse)(nil),            // 4: grover.v1.MkdirResponse
	(*RenameRequest)(nil),            // 5: grover.v1.RenameRequest
	(*RenameResponse)(nil),           // 6: grover.v1.RenameResponse
	(*FileInfo)(nil),                 // 7: grover.v1.FileInfo
	(*ListFilesRequest)(nil),         // 8: grover.v1.ListFilesRequest
	(*ListFilesResponse)(nil),        // 9: grover.v1.ListFilesResponse
	(*RemoveFileRequest)(nil),        // 10: grover.v1.RemoveFileRequest
	(*RemoveFileResponse)(nil),       // 11: grover.v1.RemoveFileResponse
	(*Credential)(nil),               // 12: grover.v1.Credential
	(*BasicDetails)(nil),             // 13: grover.v1.BasicDetails
	(*SshDetails)(nil),               // 14: grover.v1.SshDetails
	(*CreateCredentialRequest)(nil),  // 15: grover.v1.CreateCredentialRequest
	(*CreateCredentialResponse)(nil), // 16: grover.v1.CreateCredentialResponse
	(*GetCredentialRequest)(nil),     // 17: grover.v1.GetCredentialRequest
	(*GetCredentialResponse)(nil),    // 18: grover.v1.GetCredentialResponse
	(*ListCredentialsRequest)(nil),   // 19: grover.v1.ListCredentialsRequest
	(*ListCredentialsResponse)(nil),  // 20: grover.v1.ListCredentialsResponse
	(*DeleteCredentialRequest)(nil),  // 21: grover.v1.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil), // 22: grover.v1.DeleteCredentialResponse
}
var file_grover_proto_depIdxs = []int32{
	0,  // 0: grover.v1.MkdirRequest.type:type_name -> grover.v1.EndpointType
	2,  // 1: grover.v1.MkdirRequest.CredentialRef:type_name -> grover.v1.CredentialRef
	0,  // 2: grover.v1.RenameRequest.type:type_name -> grover.v1.EndpointType
	2,  // 3: grover.v1.RenameRequest.credentialRef:type_name -> grover.v1.CredentialRef
	0,  // 4: grover.v1.ListFilesRequest.type:type_name -> grover.v1.EndpointType
	2,  // 5: grover.v1.ListFilesRequest.credential_ref:type_name -> grover.v1.CredentialRef
	7,  // 6: grover.v1.ListFilesResponse.files:type_name -> grover.v1.FileInfo
	0,  // 7: grover.v1.RemoveFileRequest.type:type_name -> grover.v1.EndpointType
	2,  // 8: grover.v1.RemoveFileRequest.credential_ref:type_name -> grover.v1.CredentialRef
	1,  // 9: grover.v1.Credential.type:type_name -> grover.v1.CredentialType
	13, // 10: grover.v1.Credential.basic:type_name -> grover.v1.BasicDetails
	14, // 11: grover.v1.Credential.ssh:type_name -> grover.v1.SshDetails
	12, // 12: grover.v1.CreateCredentialRequest.credential:type_name -> grover.v1.Credential
	2,  // 13: grover.v1.GetCredentialRequest.ref:type_name -> grover.v1.CredentialRef
	12, // 14: grover.v1.GetCredentialResponse.credential:type_name -> grover.v1.Credential
	1,  // 15: grover.v1.ListCredentialsRequest.type:type_name -> grover.v1.CredentialType
	12, // 16: grover.v1.ListCredentialsResponse.credentials:type_name -> grover.v1.Credential
	2,  // 17: grover.v1.DeleteCredentialRequest.ref:type_name -> grover.v1.CredentialRef
	8,  // 18: grover.v1.FileService.List:input_type -> grover.v1.ListFilesRequest
	10, // 19: grover.v1.FileService.Remove:input_type -> grover.v1.RemoveFileRequest
	3,  // 20: grover.v1.FileService.Mkdir:input_type -> grover.v1.MkdirRequest
	5,  // 21: grover.v1.FileService.Rename:input_type -> grover.v1.RenameRequest
	15, // 22: grover.v1.CredentialService.Create:input_type -> grover.v1.CreateCredentialRequest
	17, // 23: grover.v1.CredentialService.Get:input_type -> grover.v1.GetCredentialRequest
	19, // 24: grover.v1.CredentialService.List:input_type -> grover.v1.ListCredentialsRequest
	21, // 25: grover.v1.CredentialService.Delete:input_type -> grover.v1.DeleteCredentialRequest
	9,  // 26: grover.v1.FileService.List:output_type -> grover.v1.ListFilesResponse
	11, // 27: grover.v1.FileService.Remove:output_type -> grover.v1.RemoveFileResponse
	4,  // 28: grover.v1.FileService.Mkdir:output_type -> grover.v1.MkdirResponse
	6,  // 29: grover.v1.FileService.Rename:output_type -> grover.v1.RenameResponse
	16, // 30: grover.v1.CredentialService.Create:output_type -> grover.v1.CreateCredentialResponse
	18, // 31: grover.v1.CredentialService.Get:output_type -> grover.v1.GetCredentialResponse
	20, // 32: grover.v1.CredentialService.List:output_type -> grover.v1.ListCredentialsResponse
	22, // 33: grover.v1.CredentialService.Delete:output_type -> grover.v1.DeleteCredentialResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_grover_proto_init() }
func file_grover_proto_init() {
	if File_grover_proto != nil {
		return
	}
	file_grover_proto_msgTypes[0].OneofWrappers = []any{
		(*CredentialRef_CredentialUuid)(nil),
		(*CredentialRef_CredentialName)(nil),
	}
	file_grover_proto_msgTypes[10].OneofWrappers = []any{
		(*Credential_Basic)(nil),
		(*Credential_Ssh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grover_proto_rawDesc), len(file_grover_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grover_proto_goTypes,
		DependencyIndexes: file_grover_proto_depIdxs,
		EnumInfos:         file_grover_proto_enumTypes,
		MessageInfos:      file_grover_proto_msgTypes,
	}.Build()
	File_grover_proto = out.File
	file_grover_proto_goTypes = nil
	file_grover_proto_depIdxs = nil
}
