// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: grover.proto

package groverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayControl_CreateForward_FullMethodName      = "/grover.v1.RelayControl/CreateForward"
	RelayControl_GetForward_FullMethodName         = "/grover.v1.RelayControl/GetForward"
	RelayControl_ListForwards_FullMethodName       = "/grover.v1.RelayControl/ListForwards"
	RelayControl_DeleteForward_FullMethodName      = "/grover.v1.RelayControl/DeleteForward"
	RelayControl_RenewForward_FullMethodName       = "/grover.v1.RelayControl/RenewForward"
	RelayControl_StreamForwardStats_FullMethodName = "/grover.v1.RelayControl/StreamForwardStats"
)

// RelayControlClient is the client API for RelayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayControlClient interface {
	CreateForward(ctx context.Context, in *CreateForwardRequest, opts ...grpc.CallOption) (*CreateForwardResponse, error)
	GetForward(ctx context.Context, in *GetForwardRequest, opts ...grpc.CallOption) (*GetForwardResponse, error)
	ListForwards(ctx context.Context, in *ListForwardsRequest, opts ...grpc.CallOption) (*ListForwardsResponse, error)
	DeleteForward(ctx context.Context, in *DeleteForwardRequest, opts ...grpc.CallOption) (*DeleteForwardResponse, error)
	RenewForward(ctx context.Context, in *RenewForwardRequest, opts ...grpc.CallOption) (*RenewForwardResponse, error)
	StreamForwardStats(ctx context.Context, in *StreamForwardStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ForwardSession], error)
}

type relayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayControlClient(cc grpc.ClientConnInterface) RelayControlClient {
	return &relayControlClient{cc}
}

func (c *relayControlClient) CreateForward(ctx context.Context, in *CreateForwardRequest, opts ...grpc.CallOption) (*CreateForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateForwardResponse)
	err := c.cc.Invoke(ctx, RelayControl_CreateForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) GetForward(ctx context.Context, in *GetForwardRequest, opts ...grpc.CallOption) (*GetForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForwardResponse)
	err := c.cc.Invoke(ctx, RelayControl_GetForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) ListForwards(ctx context.Context, in *ListForwardsRequest, opts ...grpc.CallOption) (*ListForwardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListForwardsResponse)
	err := c.cc.Invoke(ctx, RelayControl_ListForwards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) DeleteForward(ctx context.Context, in *DeleteForwardRequest, opts ...grpc.CallOption) (*DeleteForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteForwardResponse)
	err := c.cc.Invoke(ctx, RelayControl_DeleteForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) RenewForward(ctx context.Context, in *RenewForwardRequest, opts ...grpc.CallOption) (*RenewForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewForwardResponse)
	err := c.cc.Invoke(ctx, RelayControl_RenewForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) StreamForwardStats(ctx context.Context, in *StreamForwardStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ForwardSession], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RelayControl_ServiceDesc.Streams[0], RelayControl_StreamForwardStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamForwardStatsRequest, ForwardSession]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayControl_StreamForwardStatsClient = grpc.ServerStreamingClient[ForwardSession]

// RelayControlServer is the server API for RelayControl service.
// All implementations must embed UnimplementedRelayControlServer
// for forward compatibility.
type RelayControlServer interface {
	CreateForward(context.Context, *CreateForwardRequest) (*CreateForwardResponse, error)
	GetForward(context.Context, *GetForwardRequest) (*GetForwardResponse, error)
	ListForwards(context.Context, *ListForwardsRequest) (*ListForwardsResponse, error)
	DeleteForward(context.Context, *DeleteForwardRequest) (*DeleteForwardResponse, error)
	RenewForward(context.Context, *RenewForwardRequest) (*RenewForwardResponse, error)
	StreamForwardStats(*StreamForwardStatsRequest, grpc.ServerStreamingServer[ForwardSession]) error
	mustEmbedUnimplementedRelayControlServer()
}

// UnimplementedRelayControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayControlServer struct{}

func (UnimplementedRelayControlServer) CreateForward(context.Context, *CreateForwardRequest) (*CreateForwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateForward not implemented")
}
func (UnimplementedRelayControlServer) GetForward(context.Context, *GetForwardRequest) (*GetForwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForward not implemented")
}
func (UnimplementedRelayControlServer) ListForwards(context.Context, *ListForwardsRequest) (*ListForwardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListForwards not implemented")
}
func (UnimplementedRelayControlServer) DeleteForward(context.Context, *DeleteForwardRequest) (*DeleteForwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteForward not implemented")
}
func (UnimplementedRelayControlServer) RenewForward(context.Context, *RenewForwardRequest) (*RenewForwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewForward not implemented")
}
func (UnimplementedRelayControlServer) StreamForwardStats(*StreamForwardStatsRequest, grpc.ServerStreamingServer[ForwardSession]) error {
	return status.Errorf(codes.Unimplemented, "method StreamForwardStats not implemented")
}
func (UnimplementedRelayControlServer) mustEmbedUnimplementedRelayControlServer() {}
func (UnimplementedRelayControlServer) testEmbeddedByValue()                      {}

// UnsafeRelayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayControlServer will
// result in compilation errors.
type UnsafeRelayControlServer interface {
	mustEmbedUnimplementedRelayControlServer()
}

func RegisterRelayControlServer(s grpc.ServiceRegistrar, srv RelayControlServer) {
	// If the following call pancis, it indicates UnimplementedRelayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayControl_ServiceDesc, srv)
}

func _RelayControl_CreateForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).CreateForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_CreateForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).CreateForward(ctx, req.(*CreateForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_GetForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).GetForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_GetForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).GetForward(ctx, req.(*GetForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_ListForwards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListForwardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).ListForwards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_ListForwards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).ListForwards(ctx, req.(*ListForwardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_DeleteForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).DeleteForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_DeleteForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).DeleteForward(ctx, req.(*DeleteForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_RenewForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).RenewForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_RenewForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).RenewForward(ctx, req.(*RenewForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_StreamForwardStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamForwardStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RelayControlServer).StreamForwardStats(m, &grpc.GenericServerStream[StreamForwardStatsRequest, ForwardSession]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayControl_StreamForwardStatsServer = grpc.ServerStreamingServer[ForwardSession]

// RelayControl_ServiceDesc is the grpc.ServiceDesc for RelayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.RelayControl",
	HandlerType: (*RelayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForward",
			Handler:    _RelayControl_CreateForward_Handler,
		},
		{
			MethodName: "GetForward",
			Handler:    _RelayControl_GetForward_Handler,
		},
		{
			MethodName: "ListForwards",
			Handler:    _RelayControl_ListForwards_Handler,
		},
		{
			MethodName: "DeleteForward",
			Handler:    _RelayControl_DeleteForward_Handler,
		},
		{
			MethodName: "RenewForward",
			Handler:    _RelayControl_RenewForward_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamForwardStats",
			Handler:       _RelayControl_StreamForwardStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grover.proto",
}

const (
	RouteConfigControl_PutRoute_FullMethodName    = "/grover.v1.RouteConfigControl/PutRoute"
	RouteConfigControl_GetRoute_FullMethodName    = "/grover.v1.RouteConfigControl/GetRoute"
	RouteConfigControl_ListRoutes_FullMethodName  = "/grover.v1.RouteConfigControl/ListRoutes"
	RouteConfigControl_DeleteRoute_FullMethodName = "/grover.v1.RouteConfigControl/DeleteRoute"
)

// RouteConfigControlClient is the client API for RouteConfigControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteConfigControlClient interface {
	PutRoute(ctx context.Context, in *PutRouteRequest, opts ...grpc.CallOption) (*PutRouteResponse, error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
}

type routeConfigControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteConfigControlClient(cc grpc.ClientConnInterface) RouteConfigControlClient {
	return &routeConfigControlClient{cc}
}

func (c *routeConfigControlClient) PutRoute(ctx context.Context, in *PutRouteRequest, opts ...grpc.CallOption) (*PutRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutRouteResponse)
	err := c.cc.Invoke(ctx, RouteConfigControl_PutRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeConfigControlClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, RouteConfigControl_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeConfigControlClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, RouteConfigControl_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeConfigControlClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, RouteConfigControl_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteConfigControlServer is the server API for RouteConfigControl service.
// All implementations must embed UnimplementedRouteConfigControlServer
// for forward compatibility.
type RouteConfigControlServer interface {
	PutRoute(context.Context, *PutRouteRequest) (*PutRouteResponse, error)
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	mustEmbedUnimplementedRouteConfigControlServer()
}

// UnimplementedRouteConfigControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteConfigControlServer struct{}

func (UnimplementedRouteConfigControlServer) PutRoute(context.Context, *PutRouteRequest) (*PutRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutRoute not implemented")
}
func (UnimplementedRouteConfigControlServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedRouteConfigControlServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedRouteConfigControlServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedRouteConfigControlServer) mustEmbedUnimplementedRouteConfigControlServer() {}
func (UnimplementedRouteConfigControlServer) testEmbeddedByValue()                            {}

// UnsafeRouteConfigControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteConfigControlServer will
// result in compilation errors.
type UnsafeRouteConfigControlServer interface {
	mustEmbedUnimplementedRouteConfigControlServer()
}

func RegisterRouteConfigControlServer(s grpc.ServiceRegistrar, srv RouteConfigControlServer) {
	// If the following call pancis, it indicates UnimplementedRouteConfigControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteConfigControl_ServiceDesc, srv)
}

func _RouteConfigControl_PutRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteConfigControlServer).PutRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteConfigControl_PutRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteConfigControlServer).PutRoute(ctx, req.(*PutRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteConfigControl_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteConfigControlServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteConfigControl_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteConfigControlServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteConfigControl_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteConfigControlServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteConfigControl_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteConfigControlServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteConfigControl_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteConfigControlServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteConfigControl_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteConfigControlServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteConfigControl_ServiceDesc is the grpc.ServiceDesc for RouteConfigControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteConfigControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.RouteConfigControl",
	HandlerType: (*RouteConfigControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutRoute",
			Handler:    _RouteConfigControl_PutRoute_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _RouteConfigControl_GetRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _RouteConfigControl_ListRoutes_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _RouteConfigControl_DeleteRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grover.proto",
}

const (
	RouteSessionControl_CreateRouteSession_FullMethodName      = "/grover.v1.RouteSessionControl/CreateRouteSession"
	RouteSessionControl_GetRouteSession_FullMethodName         = "/grover.v1.RouteSessionControl/GetRouteSession"
	RouteSessionControl_ListRouteSessions_FullMethodName       = "/grover.v1.RouteSessionControl/ListRouteSessions"
	RouteSessionControl_DeleteRouteSession_FullMethodName      = "/grover.v1.RouteSessionControl/DeleteRouteSession"
	RouteSessionControl_AbortRouteSession_FullMethodName       = "/grover.v1.RouteSessionControl/AbortRouteSession"
	RouteSessionControl_UpdateRouteSessionState_FullMethodName = "/grover.v1.RouteSessionControl/UpdateRouteSessionState"
	RouteSessionControl_StreamRouteSessionStats_FullMethodName = "/grover.v1.RouteSessionControl/StreamRouteSessionStats"
)

// RouteSessionControlClient is the client API for RouteSessionControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteSessionControlClient interface {
	CreateRouteSession(ctx context.Context, in *CreateRouteSessionRequest, opts ...grpc.CallOption) (*CreateRouteSessionResponse, error)
	GetRouteSession(ctx context.Context, in *GetRouteSessionRequest, opts ...grpc.CallOption) (*GetRouteSessionResponse, error)
	ListRouteSessions(ctx context.Context, in *ListRouteSessionsRequest, opts ...grpc.CallOption) (*ListRouteSessionsResponse, error)
	DeleteRouteSession(ctx context.Context, in *DeleteRouteSessionRequest, opts ...grpc.CallOption) (*DeleteRouteSessionResponse, error)
	AbortRouteSession(ctx context.Context, in *AbortRouteSessionRequest, opts ...grpc.CallOption) (*AbortRouteSessionResponse, error)
	UpdateRouteSessionState(ctx context.Context, in *UpdateRouteSessionStateRequest, opts ...grpc.CallOption) (*UpdateRouteSessionStateResponse, error)
	StreamRouteSessionStats(ctx context.Context, in *StreamRouteSessionStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteSession], error)
}

type routeSessionControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteSessionControlClient(cc grpc.ClientConnInterface) RouteSessionControlClient {
	return &routeSessionControlClient{cc}
}

func (c *routeSessionControlClient) CreateRouteSession(ctx context.Context, in *CreateRouteSessionRequest, opts ...grpc.CallOption) (*CreateRouteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRouteSessionResponse)
	err := c.cc.Invoke(ctx, RouteSessionControl_CreateRouteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeSessionControlClient) GetRouteSession(ctx context.Context, in *GetRouteSessionRequest, opts ...grpc.CallOption) (*GetRouteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteSessionResponse)
	err := c.cc.Invoke(ctx, RouteSessionControl_GetRouteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeSessionControlClient) ListRouteSessions(ctx context.Context, in *ListRouteSessionsRequest, opts ...grpc.CallOption) (*ListRouteSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRouteSessionsResponse)
	err := c.cc.Invoke(ctx, RouteSessionControl_ListRouteSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeSessionControlClient) DeleteRouteSession(ctx context.Context, in *DeleteRouteSessionRequest, opts ...grpc.CallOption) (*DeleteRouteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteSessionResponse)
	err := c.cc.Invoke(ctx, RouteSessionControl_DeleteRouteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeSessionControlClient) AbortRouteSession(ctx context.Context, in *AbortRouteSessionRequest, opts ...grpc.CallOption) (*AbortRouteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortRouteSessionResponse)
	err := c.cc.Invoke(ctx, RouteSessionControl_AbortRouteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeSessionControlClient) UpdateRouteSessionState(ctx context.Context, in *UpdateRouteSessionStateRequest, opts ...grpc.CallOption) (*UpdateRouteSessionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRouteSessionStateResponse)
	err := c.cc.Invoke(ctx, RouteSessionControl_UpdateRouteSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeSessionControlClient) StreamRouteSessionStats(ctx context.Context, in *StreamRouteSessionStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteSession], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouteSessionControl_ServiceDesc.Streams[0], RouteSessionControl_StreamRouteSessionStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRouteSessionStatsRequest, RouteSession]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteSessionControl_StreamRouteSessionStatsClient = grpc.ServerStreamingClient[RouteSession]

// RouteSessionControlServer is the server API for RouteSessionControl service.
// All implementations must embed UnimplementedRouteSessionControlServer
// for forward compatibility.
type RouteSessionControlServer interface {
	CreateRouteSession(context.Context, *CreateRouteSessionRequest) (*CreateRouteSessionResponse, error)
	GetRouteSession(context.Context, *GetRouteSessionRequest) (*GetRouteSessionResponse, error)
	ListRouteSessions(context.Context, *ListRouteSessionsRequest) (*ListRouteSessionsResponse, error)
	DeleteRouteSession(context.Context, *DeleteRouteSessionRequest) (*DeleteRouteSessionResponse, error)
	AbortRouteSession(context.Context, *AbortRouteSessionRequest) (*AbortRouteSessionResponse, error)
	UpdateRouteSessionState(context.Context, *UpdateRouteSessionStateRequest) (*UpdateRouteSessionStateResponse, error)
	StreamRouteSessionStats(*StreamRouteSessionStatsRequest, grpc.ServerStreamingServer[RouteSession]) error
	mustEmbedUnimplementedRouteSessionControlServer()
}

// UnimplementedRouteSessionControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteSessionControlServer struct{}

func (UnimplementedRouteSessionControlServer) CreateRouteSession(context.Context, *CreateRouteSessionRequest) (*CreateRouteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRouteSession not implemented")
}
func (UnimplementedRouteSessionControlServer) GetRouteSession(context.Context, *GetRouteSessionRequest) (*GetRouteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRouteSession not implemented")
}
func (UnimplementedRouteSessionControlServer) ListRouteSessions(context.Context, *ListRouteSessionsRequest) (*ListRouteSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRouteSessions not implemented")
}
func (UnimplementedRouteSessionControlServer) DeleteRouteSession(context.Context, *DeleteRouteSessionRequest) (*DeleteRouteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRouteSession not implemented")
}
func (UnimplementedRouteSessionControlServer) AbortRouteSession(context.Context, *AbortRouteSessionRequest) (*AbortRouteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortRouteSession not implemented")
}
func (UnimplementedRouteSessionControlServer) UpdateRouteSessionState(context.Context, *UpdateRouteSessionStateRequest) (*UpdateRouteSessionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRouteSessionState not implemented")
}
func (UnimplementedRouteSessionControlServer) StreamRouteSessionStats(*StreamRouteSessionStatsRequest, grpc.ServerStreamingServer[RouteSession]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRouteSessionStats not implemented")
}
func (UnimplementedRouteSessionControlServer) mustEmbedUnimplementedRouteSessionControlServer() {}
func (UnimplementedRouteSessionControlServer) testEmbeddedByValue()                             {}

// UnsafeRouteSessionControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteSessionControlServer will
// result in compilation errors.
type UnsafeRouteSessionControlServer interface {
	mustEmbedUnimplementedRouteSessionControlServer()
}

func RegisterRouteSessionControlServer(s grpc.ServiceRegistrar, srv RouteSessionControlServer) {
	// If the following call pancis, it indicates UnimplementedRouteSessionControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteSessionControl_ServiceDesc, srv)
}

func _RouteSessionControl_CreateRouteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteSessionControlServer).CreateRouteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteSessionControl_CreateRouteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteSessionControlServer).CreateRouteSession(ctx, req.(*CreateRouteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteSessionControl_GetRouteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteSessionControlServer).GetRouteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteSessionControl_GetRouteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteSessionControlServer).GetRouteSession(ctx, req.(*GetRouteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteSessionControl_ListRouteSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRouteSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteSessionControlServer).ListRouteSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteSessionControl_ListRouteSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteSessionControlServer).ListRouteSessions(ctx, req.(*ListRouteSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteSessionControl_DeleteRouteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteSessionControlServer).DeleteRouteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteSessionControl_DeleteRouteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteSessionControlServer).DeleteRouteSession(ctx, req.(*DeleteRouteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteSessionControl_AbortRouteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRouteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteSessionControlServer).AbortRouteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteSessionControl_AbortRouteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteSessionControlServer).AbortRouteSession(ctx, req.(*AbortRouteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteSessionControl_UpdateRouteSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteSessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteSessionControlServer).UpdateRouteSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteSessionControl_UpdateRouteSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteSessionControlServer).UpdateRouteSessionState(ctx, req.(*UpdateRouteSessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteSessionControl_StreamRouteSessionStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRouteSessionStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteSessionControlServer).StreamRouteSessionStats(m, &grpc.GenericServerStream[StreamRouteSessionStatsRequest, RouteSession]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteSessionControl_StreamRouteSessionStatsServer = grpc.ServerStreamingServer[RouteSession]

// RouteSessionControl_ServiceDesc is the grpc.ServiceDesc for RouteSessionControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteSessionControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.RouteSessionControl",
	HandlerType: (*RouteSessionControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRouteSession",
			Handler:    _RouteSessionControl_CreateRouteSession_Handler,
		},
		{
			MethodName: "GetRouteSession",
			Handler:    _RouteSessionControl_GetRouteSession_Handler,
		},
		{
			MethodName: "ListRouteSessions",
			Handler:    _RouteSessionControl_ListRouteSessions_Handler,
		},
		{
			MethodName: "DeleteRouteSession",
			Handler:    _RouteSessionControl_DeleteRouteSession_Handler,
		},
		{
			MethodName: "AbortRouteSession",
			Handler:    _RouteSessionControl_AbortRouteSession_Handler,
		},
		{
			MethodName: "UpdateRouteSessionState",
			Handler:    _RouteSessionControl_UpdateRouteSessionState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRouteSessionStats",
			Handler:       _RouteSessionControl_StreamRouteSessionStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grover.proto",
}

const (
	TransferJobControl_PrepareTransferEndpoint_FullMethodName   = "/grover.v1.TransferJobControl/PrepareTransferEndpoint"
	TransferJobControl_StartTransferJob_FullMethodName          = "/grover.v1.TransferJobControl/StartTransferJob"
	TransferJobControl_GetTransferJob_FullMethodName            = "/grover.v1.TransferJobControl/GetTransferJob"
	TransferJobControl_ListTransferJobs_FullMethodName          = "/grover.v1.TransferJobControl/ListTransferJobs"
	TransferJobControl_AbortTransferJob_FullMethodName          = "/grover.v1.TransferJobControl/AbortTransferJob"
	TransferJobControl_UpdateTransferConcurrency_FullMethodName = "/grover.v1.TransferJobControl/UpdateTransferConcurrency"
	TransferJobControl_UpdateTransferTuning_FullMethodName      = "/grover.v1.TransferJobControl/UpdateTransferTuning"
	TransferJobControl_StreamTransferStats_FullMethodName       = "/grover.v1.TransferJobControl/StreamTransferStats"
)

// TransferJobControlClient is the client API for TransferJobControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferJobControlClient interface {
	PrepareTransferEndpoint(ctx context.Context, in *PrepareTransferEndpointRequest, opts ...grpc.CallOption) (*PrepareTransferEndpointResponse, error)
	StartTransferJob(ctx context.Context, in *StartTransferJobRequest, opts ...grpc.CallOption) (*StartTransferJobResponse, error)
	GetTransferJob(ctx context.Context, in *GetTransferJobRequest, opts ...grpc.CallOption) (*GetTransferJobResponse, error)
	ListTransferJobs(ctx context.Context, in *ListTransferJobsRequest, opts ...grpc.CallOption) (*ListTransferJobsResponse, error)
	AbortTransferJob(ctx context.Context, in *AbortTransferJobRequest, opts ...grpc.CallOption) (*AbortTransferJobResponse, error)
	UpdateTransferConcurrency(ctx context.Context, in *UpdateTransferConcurrencyRequest, opts ...grpc.CallOption) (*UpdateTransferConcurrencyResponse, error)
	UpdateTransferTuning(ctx context.Context, in *UpdateTransferTuningRequest, opts ...grpc.CallOption) (*UpdateTransferTuningResponse, error)
	StreamTransferStats(ctx context.Context, in *StreamTransferStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferJob], error)
}

type transferJobControlClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferJobControlClient(cc grpc.ClientConnInterface) TransferJobControlClient {
	return &transferJobControlClient{cc}
}

func (c *transferJobControlClient) PrepareTransferEndpoint(ctx context.Context, in *PrepareTransferEndpointRequest, opts ...grpc.CallOption) (*PrepareTransferEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTransferEndpointResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_PrepareTransferEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) StartTransferJob(ctx context.Context, in *StartTransferJobRequest, opts ...grpc.CallOption) (*StartTransferJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTransferJobResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_StartTransferJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) GetTransferJob(ctx context.Context, in *GetTransferJobRequest, opts ...grpc.CallOption) (*GetTransferJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransferJobResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_GetTransferJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) ListTransferJobs(ctx context.Context, in *ListTransferJobsRequest, opts ...grpc.CallOption) (*ListTransferJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransferJobsResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_ListTransferJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) AbortTransferJob(ctx context.Context, in *AbortTransferJobRequest, opts ...grpc.CallOption) (*AbortTransferJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortTransferJobResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_AbortTransferJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) UpdateTransferConcurrency(ctx context.Context, in *UpdateTransferConcurrencyRequest, opts ...grpc.CallOption) (*UpdateTransferConcurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTransferConcurrencyResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_UpdateTransferConcurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) UpdateTransferTuning(ctx context.Context, in *UpdateTransferTuningRequest, opts ...grpc.CallOption) (*UpdateTransferTuningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTransferTuningResponse)
	err := c.cc.Invoke(ctx, TransferJobControl_UpdateTransferTuning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferJobControlClient) StreamTransferStats(ctx context.Context, in *StreamTransferStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferJob], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransferJobControl_ServiceDesc.Streams[0], TransferJobControl_StreamTransferStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTransferStatsRequest, TransferJob]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferJobControl_StreamTransferStatsClient = grpc.ServerStreamingClient[TransferJob]

// TransferJobControlServer is the server API for TransferJobControl service.
// All implementations must embed UnimplementedTransferJobControlServer
// for forward compatibility.
type TransferJobControlServer interface {
	PrepareTransferEndpoint(context.Context, *PrepareTransferEndpointRequest) (*PrepareTransferEndpointResponse, error)
	StartTransferJob(context.Context, *StartTransferJobRequest) (*StartTransferJobResponse, error)
	GetTransferJob(context.Context, *GetTransferJobRequest) (*GetTransferJobResponse, error)
	ListTransferJobs(context.Context, *ListTransferJobsRequest) (*ListTransferJobsResponse, error)
	AbortTransferJob(context.Context, *AbortTransferJobRequest) (*AbortTransferJobResponse, error)
	UpdateTransferConcurrency(context.Context, *UpdateTransferConcurrencyRequest) (*UpdateTransferConcurrencyResponse, error)
	UpdateTransferTuning(context.Context, *UpdateTransferTuningRequest) (*UpdateTransferTuningResponse, error)
	StreamTransferStats(*StreamTransferStatsRequest, grpc.ServerStreamingServer[TransferJob]) error
	mustEmbedUnimplementedTransferJobControlServer()
}

// UnimplementedTransferJobControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransferJobControlServer struct{}

func (UnimplementedTransferJobControlServer) PrepareTransferEndpoint(context.Context, *PrepareTransferEndpointRequest) (*PrepareTransferEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTransferEndpoint not implemented")
}
func (UnimplementedTransferJobControlServer) StartTransferJob(context.Context, *StartTransferJobRequest) (*StartTransferJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTransferJob not implemented")
}
func (UnimplementedTransferJobControlServer) GetTransferJob(context.Context, *GetTransferJobRequest) (*GetTransferJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransferJob not implemented")
}
func (UnimplementedTransferJobControlServer) ListTransferJobs(context.Context, *ListTransferJobsRequest) (*ListTransferJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransferJobs not implemented")
}
func (UnimplementedTransferJobControlServer) AbortTransferJob(context.Context, *AbortTransferJobRequest) (*AbortTransferJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortTransferJob not implemented")
}
func (UnimplementedTransferJobControlServer) UpdateTransferConcurrency(context.Context, *UpdateTransferConcurrencyRequest) (*UpdateTransferConcurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransferConcurrency not implemented")
}
func (UnimplementedTransferJobControlServer) UpdateTransferTuning(context.Context, *UpdateTransferTuningRequest) (*UpdateTransferTuningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransferTuning not implemented")
}
func (UnimplementedTransferJobControlServer) StreamTransferStats(*StreamTransferStatsRequest, grpc.ServerStreamingServer[TransferJob]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTransferStats not implemented")
}
func (UnimplementedTransferJobControlServer) mustEmbedUnimplementedTransferJobControlServer() {}
func (UnimplementedTransferJobControlServer) testEmbeddedByValue()                            {}

// UnsafeTransferJobControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferJobControlServer will
// result in compilation errors.
type UnsafeTransferJobControlServer interface {
	mustEmbedUnimplementedTransferJobControlServer()
}

func RegisterTransferJobControlServer(s grpc.ServiceRegistrar, srv TransferJobControlServer) {
	// If the following call pancis, it indicates UnimplementedTransferJobControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransferJobControl_ServiceDesc, srv)
}

func _TransferJobControl_PrepareTransferEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTransferEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).PrepareTransferEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_PrepareTransferEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).PrepareTransferEndpoint(ctx, req.(*PrepareTransferEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_StartTransferJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTransferJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).StartTransferJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_StartTransferJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).StartTransferJob(ctx, req.(*StartTransferJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_GetTransferJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).GetTransferJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_GetTransferJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).GetTransferJob(ctx, req.(*GetTransferJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_ListTransferJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransferJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).ListTransferJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_ListTransferJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).ListTransferJobs(ctx, req.(*ListTransferJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_AbortTransferJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortTransferJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).AbortTransferJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_AbortTransferJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).AbortTransferJob(ctx, req.(*AbortTransferJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_UpdateTransferConcurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransferConcurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).UpdateTransferConcurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_UpdateTransferConcurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).UpdateTransferConcurrency(ctx, req.(*UpdateTransferConcurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_UpdateTransferTuning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransferTuningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferJobControlServer).UpdateTransferTuning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferJobControl_UpdateTransferTuning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferJobControlServer).UpdateTransferTuning(ctx, req.(*UpdateTransferTuningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferJobControl_StreamTransferStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTransferStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferJobControlServer).StreamTransferStats(m, &grpc.GenericServerStream[StreamTransferStatsRequest, TransferJob]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferJobControl_StreamTransferStatsServer = grpc.ServerStreamingServer[TransferJob]

// TransferJobControl_ServiceDesc is the grpc.ServiceDesc for TransferJobControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferJobControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.TransferJobControl",
	HandlerType: (*TransferJobControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareTransferEndpoint",
			Handler:    _TransferJobControl_PrepareTransferEndpoint_Handler,
		},
		{
			MethodName: "StartTransferJob",
			Handler:    _TransferJobControl_StartTransferJob_Handler,
		},
		{
			MethodName: "GetTransferJob",
			Handler:    _TransferJobControl_GetTransferJob_Handler,
		},
		{
			MethodName: "ListTransferJobs",
			Handler:    _TransferJobControl_ListTransferJobs_Handler,
		},
		{
			MethodName: "AbortTransferJob",
			Handler:    _TransferJobControl_AbortTransferJob_Handler,
		},
		{
			MethodName: "UpdateTransferConcurrency",
			Handler:    _TransferJobControl_UpdateTransferConcurrency_Handler,
		},
		{
			MethodName: "UpdateTransferTuning",
			Handler:    _TransferJobControl_UpdateTransferTuning_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTransferStats",
			Handler:       _TransferJobControl_StreamTransferStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grover.proto",
}

const (
	JobHistoryControl_ListJobHistory_FullMethodName   = "/grover.v1.JobHistoryControl/ListJobHistory"
	JobHistoryControl_GetJobManifest_FullMethodName   = "/grover.v1.JobHistoryControl/GetJobManifest"
	JobHistoryControl_GetJobFinal_FullMethodName      = "/grover.v1.JobHistoryControl/GetJobFinal"
	JobHistoryControl_ListJobSnapshots_FullMethodName = "/grover.v1.JobHistoryControl/ListJobSnapshots"
	JobHistoryControl_ListJobEnergy_FullMethodName    = "/grover.v1.JobHistoryControl/ListJobEnergy"
)

// JobHistoryControlClient is the client API for JobHistoryControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobHistoryControlClient interface {
	ListJobHistory(ctx context.Context, in *ListJobHistoryRequest, opts ...grpc.CallOption) (*ListJobHistoryResponse, error)
	GetJobManifest(ctx context.Context, in *GetJobManifestRequest, opts ...grpc.CallOption) (*GetJobManifestResponse, error)
	GetJobFinal(ctx context.Context, in *GetJobFinalRequest, opts ...grpc.CallOption) (*GetJobFinalResponse, error)
	ListJobSnapshots(ctx context.Context, in *ListJobSnapshotsRequest, opts ...grpc.CallOption) (*ListJobSnapshotsResponse, error)
	ListJobEnergy(ctx context.Context, in *ListJobEnergyRequest, opts ...grpc.CallOption) (*ListJobEnergyResponse, error)
}

type jobHistoryControlClient struct {
	cc grpc.ClientConnInterface
}

func NewJobHistoryControlClient(cc grpc.ClientConnInterface) JobHistoryControlClient {
	return &jobHistoryControlClient{cc}
}

func (c *jobHistoryControlClient) ListJobHistory(ctx context.Context, in *ListJobHistoryRequest, opts ...grpc.CallOption) (*ListJobHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobHistoryResponse)
	err := c.cc.Invoke(ctx, JobHistoryControl_ListJobHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobHistoryControlClient) GetJobManifest(ctx context.Context, in *GetJobManifestRequest, opts ...grpc.CallOption) (*GetJobManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobManifestResponse)
	err := c.cc.Invoke(ctx, JobHistoryControl_GetJobManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobHistoryControlClient) GetJobFinal(ctx context.Context, in *GetJobFinalRequest, opts ...grpc.CallOption) (*GetJobFinalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobFinalResponse)
	err := c.cc.Invoke(ctx, JobHistoryControl_GetJobFinal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobHistoryControlClient) ListJobSnapshots(ctx context.Context, in *ListJobSnapshotsRequest, opts ...grpc.CallOption) (*ListJobSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobSnapshotsResponse)
	err := c.cc.Invoke(ctx, JobHistoryControl_ListJobSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobHistoryControlClient) ListJobEnergy(ctx context.Context, in *ListJobEnergyRequest, opts ...grpc.CallOption) (*ListJobEnergyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobEnergyResponse)
	err := c.cc.Invoke(ctx, JobHistoryControl_ListJobEnergy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobHistoryControlServer is the server API for JobHistoryControl service.
// All implementations must embed UnimplementedJobHistoryControlServer
// for forward compatibility.
type JobHistoryControlServer interface {
	ListJobHistory(context.Context, *ListJobHistoryRequest) (*ListJobHistoryResponse, error)
	GetJobManifest(context.Context, *GetJobManifestRequest) (*GetJobManifestResponse, error)
	GetJobFinal(context.Context, *GetJobFinalRequest) (*GetJobFinalResponse, error)
	ListJobSnapshots(context.Context, *ListJobSnapshotsRequest) (*ListJobSnapshotsResponse, error)
	ListJobEnergy(context.Context, *ListJobEnergyRequest) (*ListJobEnergyResponse, error)
	mustEmbedUnimplementedJobHistoryControlServer()
}

// UnimplementedJobHistoryControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobHistoryControlServer struct{}

func (UnimplementedJobHistoryControlServer) ListJobHistory(context.Context, *ListJobHistoryRequest) (*ListJobHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobHistory not implemented")
}
func (UnimplementedJobHistoryControlServer) GetJobManifest(context.Context, *GetJobManifestRequest) (*GetJobManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobManifest not implemented")
}
func (UnimplementedJobHistoryControlServer) GetJobFinal(context.Context, *GetJobFinalRequest) (*GetJobFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobFinal not implemented")
}
func (UnimplementedJobHistoryControlServer) ListJobSnapshots(context.Context, *ListJobSnapshotsRequest) (*ListJobSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobSnapshots not implemented")
}
func (UnimplementedJobHistoryControlServer) ListJobEnergy(context.Context, *ListJobEnergyRequest) (*ListJobEnergyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobEnergy not implemented")
}
func (UnimplementedJobHistoryControlServer) mustEmbedUnimplementedJobHistoryControlServer() {}
func (UnimplementedJobHistoryControlServer) testEmbeddedByValue()                           {}

// UnsafeJobHistoryControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobHistoryControlServer will
// result in compilation errors.
type UnsafeJobHistoryControlServer interface {
	mustEmbedUnimplementedJobHistoryControlServer()
}

func RegisterJobHistoryControlServer(s grpc.ServiceRegistrar, srv JobHistoryControlServer) {
	// If the following call pancis, it indicates UnimplementedJobHistoryControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobHistoryControl_ServiceDesc, srv)
}

func _JobHistoryControl_ListJobHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHistoryControlServer).ListJobHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobHistoryControl_ListJobHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHistoryControlServer).ListJobHistory(ctx, req.(*ListJobHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobHistoryControl_GetJobManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHistoryControlServer).GetJobManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobHistoryControl_GetJobManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHistoryControlServer).GetJobManifest(ctx, req.(*GetJobManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobHistoryControl_GetJobFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHistoryControlServer).GetJobFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobHistoryControl_GetJobFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHistoryControlServer).GetJobFinal(ctx, req.(*GetJobFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobHistoryControl_ListJobSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHistoryControlServer).ListJobSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobHistoryControl_ListJobSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHistoryControlServer).ListJobSnapshots(ctx, req.(*ListJobSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobHistoryControl_ListJobEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobHistoryControlServer).ListJobEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobHistoryControl_ListJobEnergy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobHistoryControlServer).ListJobEnergy(ctx, req.(*ListJobEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobHistoryControl_ServiceDesc is the grpc.ServiceDesc for JobHistoryControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobHistoryControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.JobHistoryControl",
	HandlerType: (*JobHistoryControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobHistory",
			Handler:    _JobHistoryControl_ListJobHistory_Handler,
		},
		{
			MethodName: "GetJobManifest",
			Handler:    _JobHistoryControl_GetJobManifest_Handler,
		},
		{
			MethodName: "GetJobFinal",
			Handler:    _JobHistoryControl_GetJobFinal_Handler,
		},
		{
			MethodName: "ListJobSnapshots",
			Handler:    _JobHistoryControl_ListJobSnapshots_Handler,
		},
		{
			MethodName: "ListJobEnergy",
			Handler:    _JobHistoryControl_ListJobEnergy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grover.proto",
}

const (
	FileService_List_FullMethodName   = "/grover.v1.FileService/List"
	FileService_Remove_FullMethodName = "/grover.v1.FileService/Remove"
	FileService_Mkdir_FullMethodName  = "/grover.v1.FileService/Mkdir"
	FileService_Rename_FullMethodName = "/grover.v1.FileService/Rename"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	List(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	Remove(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) List(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, FileService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Remove(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFileResponse)
	err := c.cc.Invoke(ctx, FileService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, FileService_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, FileService_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	List(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	Remove(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error)
	Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) List(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedFileServiceServer) Remove(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedFileServiceServer) Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedFileServiceServer) Rename(context.Context, *RenameRequest) (*RenameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).List(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Remove(ctx, req.(*RemoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _FileService_List_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _FileService_Remove_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _FileService_Mkdir_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _FileService_Rename_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grover.proto",
}

const (
	CredentialService_Create_FullMethodName = "/grover.v1.CredentialService/Create"
	CredentialService_Get_FullMethodName    = "/grover.v1.CredentialService/Get"
	CredentialService_List_FullMethodName   = "/grover.v1.CredentialService/List"
	CredentialService_Delete_FullMethodName = "/grover.v1.CredentialService/Delete"
)

// CredentialServiceClient is the client API for CredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialServiceClient interface {
	Create(ctx context.Context, in *CreateCredentialRequest, opts ...grpc.CallOption) (*CreateCredentialResponse, error)
	Get(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error)
	List(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error)
	Delete(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
}

type credentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialServiceClient(cc grpc.ClientConnInterface) CredentialServiceClient {
	return &credentialServiceClient{cc}
}

func (c *credentialServiceClient) Create(ctx context.Context, in *CreateCredentialRequest, opts ...grpc.CallOption) (*CreateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Get(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) List(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialsResponse)
	err := c.cc.Invoke(ctx, CredentialService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Delete(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialServiceServer is the server API for CredentialService service.
// All implementations must embed UnimplementedCredentialServiceServer
// for forward compatibility.
type CredentialServiceServer interface {
	Create(context.Context, *CreateCredentialRequest) (*CreateCredentialResponse, error)
	Get(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error)
	List(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error)
	Delete(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	mustEmbedUnimplementedCredentialServiceServer()
}

// UnimplementedCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialServiceServer struct{}

func (UnimplementedCredentialServiceServer) Create(context.Context, *CreateCredentialRequest) (*CreateCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCredentialServiceServer) Get(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCredentialServiceServer) List(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCredentialServiceServer) Delete(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCredentialServiceServer) mustEmbedUnimplementedCredentialServiceServer() {}
func (UnimplementedCredentialServiceServer) testEmbeddedByValue()                           {}

// UnsafeCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialServiceServer will
// result in compilation errors.
type UnsafeCredentialServiceServer interface {
	mustEmbedUnimplementedCredentialServiceServer()
}

func RegisterCredentialServiceServer(s grpc.ServiceRegistrar, srv CredentialServiceServer) {
	// If the following call pancis, it indicates UnimplementedCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialService_ServiceDesc, srv)
}

func _CredentialService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Create(ctx, req.(*CreateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Get(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).List(ctx, req.(*ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Delete(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialService_ServiceDesc is the grpc.ServiceDesc for CredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grover.v1.CredentialService",
	HandlerType: (*CredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CredentialService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CredentialService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CredentialService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CredentialService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grover.proto",
}
