// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: grover_udp.proto

package groverudpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroverServer_StartServer_FullMethodName    = "/groverudp.v1.GroverServer/StartServer"
	GroverServer_StopServer_FullMethodName     = "/groverudp.v1.GroverServer/StopServer"
	GroverServer_ListPorts_FullMethodName      = "/groverudp.v1.GroverServer/ListPorts"
	GroverServer_DeleteUdpPorts_FullMethodName = "/groverudp.v1.GroverServer/DeleteUdpPorts"
	GroverServer_CreateUdpPorts_FullMethodName = "/groverudp.v1.GroverServer/CreateUdpPorts"
)

// GroverServerClient is the client API for GroverServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroverServerClient interface {
	StartServer(ctx context.Context, in *StartServerRequest, opts ...grpc.CallOption) (*StartServerResponse, error)
	StopServer(ctx context.Context, in *StopServerRequest, opts ...grpc.CallOption) (*StopServerResponse, error)
	ListPorts(ctx context.Context, in *ListPortRequest, opts ...grpc.CallOption) (*ListPortResponse, error)
	DeleteUdpPorts(ctx context.Context, in *DeleteUdpPortsRequest, opts ...grpc.CallOption) (*DeleteUdpPortsResponse, error)
	CreateUdpPorts(ctx context.Context, in *CreateUdpPortsRequest, opts ...grpc.CallOption) (*CreateUdpPortsResponse, error)
}

type groverServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGroverServerClient(cc grpc.ClientConnInterface) GroverServerClient {
	return &groverServerClient{cc}
}

func (c *groverServerClient) StartServer(ctx context.Context, in *StartServerRequest, opts ...grpc.CallOption) (*StartServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartServerResponse)
	err := c.cc.Invoke(ctx, GroverServer_StartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groverServerClient) StopServer(ctx context.Context, in *StopServerRequest, opts ...grpc.CallOption) (*StopServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopServerResponse)
	err := c.cc.Invoke(ctx, GroverServer_StopServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groverServerClient) ListPorts(ctx context.Context, in *ListPortRequest, opts ...grpc.CallOption) (*ListPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortResponse)
	err := c.cc.Invoke(ctx, GroverServer_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groverServerClient) DeleteUdpPorts(ctx context.Context, in *DeleteUdpPortsRequest, opts ...grpc.CallOption) (*DeleteUdpPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUdpPortsResponse)
	err := c.cc.Invoke(ctx, GroverServer_DeleteUdpPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groverServerClient) CreateUdpPorts(ctx context.Context, in *CreateUdpPortsRequest, opts ...grpc.CallOption) (*CreateUdpPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUdpPortsResponse)
	err := c.cc.Invoke(ctx, GroverServer_CreateUdpPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroverServerServer is the server API for GroverServer service.
// All implementations must embed UnimplementedGroverServerServer
// for forward compatibility.
type GroverServerServer interface {
	StartServer(context.Context, *StartServerRequest) (*StartServerResponse, error)
	StopServer(context.Context, *StopServerRequest) (*StopServerResponse, error)
	ListPorts(context.Context, *ListPortRequest) (*ListPortResponse, error)
	DeleteUdpPorts(context.Context, *DeleteUdpPortsRequest) (*DeleteUdpPortsResponse, error)
	CreateUdpPorts(context.Context, *CreateUdpPortsRequest) (*CreateUdpPortsResponse, error)
	mustEmbedUnimplementedGroverServerServer()
}

// UnimplementedGroverServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroverServerServer struct{}

func (UnimplementedGroverServerServer) StartServer(context.Context, *StartServerRequest) (*StartServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartServer not implemented")
}
func (UnimplementedGroverServerServer) StopServer(context.Context, *StopServerRequest) (*StopServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServer not implemented")
}
func (UnimplementedGroverServerServer) ListPorts(context.Context, *ListPortRequest) (*ListPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedGroverServerServer) DeleteUdpPorts(context.Context, *DeleteUdpPortsRequest) (*DeleteUdpPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUdpPorts not implemented")
}
func (UnimplementedGroverServerServer) CreateUdpPorts(context.Context, *CreateUdpPortsRequest) (*CreateUdpPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUdpPorts not implemented")
}
func (UnimplementedGroverServerServer) mustEmbedUnimplementedGroverServerServer() {}
func (UnimplementedGroverServerServer) testEmbeddedByValue()                      {}

// UnsafeGroverServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroverServerServer will
// result in compilation errors.
type UnsafeGroverServerServer interface {
	mustEmbedUnimplementedGroverServerServer()
}

func RegisterGroverServerServer(s grpc.ServiceRegistrar, srv GroverServerServer) {
	// If the following call pancis, it indicates UnimplementedGroverServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroverServer_ServiceDesc, srv)
}

func _GroverServer_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroverServerServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroverServer_StartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroverServerServer).StartServer(ctx, req.(*StartServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroverServer_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroverServerServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroverServer_StopServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroverServerServer).StopServer(ctx, req.(*StopServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroverServer_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroverServerServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroverServer_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroverServerServer).ListPorts(ctx, req.(*ListPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroverServer_DeleteUdpPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUdpPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroverServerServer).DeleteUdpPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroverServer_DeleteUdpPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroverServerServer).DeleteUdpPorts(ctx, req.(*DeleteUdpPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroverServer_CreateUdpPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUdpPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroverServerServer).CreateUdpPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroverServer_CreateUdpPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroverServerServer).CreateUdpPorts(ctx, req.(*CreateUdpPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroverServer_ServiceDesc is the grpc.ServiceDesc for GroverServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroverServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "groverudp.v1.GroverServer",
	HandlerType: (*GroverServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartServer",
			Handler:    _GroverServer_StartServer_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _GroverServer_StopServer_Handler,
		},
		{
			MethodName: "ListPorts",
			Handler:    _GroverServer_ListPorts_Handler,
		},
		{
			MethodName: "DeleteUdpPorts",
			Handler:    _GroverServer_DeleteUdpPorts_Handler,
		},
		{
			MethodName: "CreateUdpPorts",
			Handler:    _GroverServer_CreateUdpPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grover_udp.proto",
}

const (
	TransferControl_OpenSession_FullMethodName   = "/groverudp.v1.TransferControl/OpenSession"
	TransferControl_CloseSession_FullMethodName  = "/groverudp.v1.TransferControl/CloseSession"
	TransferControl_LeaseStream_FullMethodName   = "/groverudp.v1.TransferControl/LeaseStream"
	TransferControl_ReleaseStream_FullMethodName = "/groverudp.v1.TransferControl/ReleaseStream"
	TransferControl_EnumeratePath_FullMethodName = "/groverudp.v1.TransferControl/EnumeratePath"
)

// TransferControlClient is the client API for TransferControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferControlClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	LeaseStream(ctx context.Context, in *LeaseStreamRequest, opts ...grpc.CallOption) (*LeaseStreamResponse, error)
	ReleaseStream(ctx context.Context, in *ReleaseStreamRequest, opts ...grpc.CallOption) (*ReleaseStreamResponse, error)
	EnumeratePath(ctx context.Context, in *EnumeratePathRequest, opts ...grpc.CallOption) (*EnumeratePathResponse, error)
}

type transferControlClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferControlClient(cc grpc.ClientConnInterface) TransferControlClient {
	return &transferControlClient{cc}
}

func (c *transferControlClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, TransferControl_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferControlClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, TransferControl_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferControlClient) LeaseStream(ctx context.Context, in *LeaseStreamRequest, opts ...grpc.CallOption) (*LeaseStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseStreamResponse)
	err := c.cc.Invoke(ctx, TransferControl_LeaseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferControlClient) ReleaseStream(ctx context.Context, in *ReleaseStreamRequest, opts ...grpc.CallOption) (*ReleaseStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseStreamResponse)
	err := c.cc.Invoke(ctx, TransferControl_ReleaseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferControlClient) EnumeratePath(ctx context.Context, in *EnumeratePathRequest, opts ...grpc.CallOption) (*EnumeratePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumeratePathResponse)
	err := c.cc.Invoke(ctx, TransferControl_EnumeratePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferControlServer is the server API for TransferControl service.
// All implementations must embed UnimplementedTransferControlServer
// for forward compatibility.
type TransferControlServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	LeaseStream(context.Context, *LeaseStreamRequest) (*LeaseStreamResponse, error)
	ReleaseStream(context.Context, *ReleaseStreamRequest) (*ReleaseStreamResponse, error)
	EnumeratePath(context.Context, *EnumeratePathRequest) (*EnumeratePathResponse, error)
	mustEmbedUnimplementedTransferControlServer()
}

// UnimplementedTransferControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransferControlServer struct{}

func (UnimplementedTransferControlServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedTransferControlServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedTransferControlServer) LeaseStream(context.Context, *LeaseStreamRequest) (*LeaseStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaseStream not implemented")
}
func (UnimplementedTransferControlServer) ReleaseStream(context.Context, *ReleaseStreamRequest) (*ReleaseStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseStream not implemented")
}
func (UnimplementedTransferControlServer) EnumeratePath(context.Context, *EnumeratePathRequest) (*EnumeratePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnumeratePath not implemented")
}
func (UnimplementedTransferControlServer) mustEmbedUnimplementedTransferControlServer() {}
func (UnimplementedTransferControlServer) testEmbeddedByValue()                         {}

// UnsafeTransferControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferControlServer will
// result in compilation errors.
type UnsafeTransferControlServer interface {
	mustEmbedUnimplementedTransferControlServer()
}

func RegisterTransferControlServer(s grpc.ServiceRegistrar, srv TransferControlServer) {
	// If the following call pancis, it indicates UnimplementedTransferControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransferControl_ServiceDesc, srv)
}

func _TransferControl_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferControlServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferControl_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferControlServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferControl_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferControlServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferControl_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferControlServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferControl_LeaseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferControlServer).LeaseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferControl_LeaseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferControlServer).LeaseStream(ctx, req.(*LeaseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferControl_ReleaseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferControlServer).ReleaseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferControl_ReleaseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferControlServer).ReleaseStream(ctx, req.(*ReleaseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferControl_EnumeratePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumeratePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferControlServer).EnumeratePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferControl_EnumeratePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferControlServer).EnumeratePath(ctx, req.(*EnumeratePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferControl_ServiceDesc is the grpc.ServiceDesc for TransferControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "groverudp.v1.TransferControl",
	HandlerType: (*TransferControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _TransferControl_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _TransferControl_CloseSession_Handler,
		},
		{
			MethodName: "LeaseStream",
			Handler:    _TransferControl_LeaseStream_Handler,
		},
		{
			MethodName: "ReleaseStream",
			Handler:    _TransferControl_ReleaseStream_Handler,
		},
		{
			MethodName: "EnumeratePath",
			Handler:    _TransferControl_EnumeratePath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grover_udp.proto",
}
