// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: grover_udp.proto

package groverudpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSessionRequest_Mode int32

const (
	OpenSessionRequest_MODE_UNSPECIFIED OpenSessionRequest_Mode = 0
	OpenSessionRequest_READ             OpenSessionRequest_Mode = 1
	OpenSessionRequest_WRITE            OpenSessionRequest_Mode = 2
)

// Enum value maps for OpenSessionRequest_Mode.
var (
	OpenSessionRequest_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "READ",
		2: "WRITE",
	}
	OpenSessionRequest_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"READ":             1,
		"WRITE":            2,
	}
)

func (x OpenSessionRequest_Mode) Enum() *OpenSessionRequest_Mode {
	p := new(OpenSessionRequest_Mode)
	*p = x
	return p
}

func (x OpenSessionRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenSessionRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_grover_udp_proto_enumTypes[0].Descriptor()
}

func (OpenSessionRequest_Mode) Type() protoreflect.EnumType {
	return &file_grover_udp_proto_enumTypes[0]
}

func (x OpenSessionRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenSessionRequest_Mode.Descriptor instead.
func (OpenSessionRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{0, 0}
}

type OpenSessionRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Mode            OpenSessionRequest_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=groverudp.v1.OpenSessionRequest_Mode" json:"mode,omitempty"`
	Path            string                  `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                               // Object path
	Size            int64                   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                                              // Used when mode=WRITE; -1 if unknown
	VerifyChecksum  bool                    `protobuf:"varint,4,opt,name=verify_checksum,json=verifyChecksum,proto3" json:"verify_checksum,omitempty"`    // Request checksum in FIN
	ParallelStreams uint32                  `protobuf:"varint,5,opt,name=parallel_streams,json=parallelStreams,proto3" json:"parallel_streams,omitempty"` // Number of UDP streams client wants
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_grover_udp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetMode() OpenSessionRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return OpenSessionRequest_MODE_UNSPECIFIED
}

func (x *OpenSessionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenSessionRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OpenSessionRequest) GetVerifyChecksum() bool {
	if x != nil {
		return x.VerifyChecksum
	}
	return false
}

func (x *OpenSessionRequest) GetParallelStreams() uint32 {
	if x != nil {
		return x.ParallelStreams
	}
	return 0
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`         // 16-byte UUID
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                  // HMAC’d cookie for UDP HELO
	ServerHost    string                 `protobuf:"bytes,3,opt,name=server_host,json=serverHost,proto3" json:"server_host,omitempty"`      // UDP endpoint host
	ServerPort    uint32                 `protobuf:"varint,4,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`     // UDP port (can be shared across streams)
	StreamIds     []uint32               `protobuf:"varint,5,rep,packed,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"` // One per parallel stream
	MtuHint       uint32                 `protobuf:"varint,6,opt,name=mtu_hint,json=mtuHint,proto3" json:"mtu_hint,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_grover_udp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionResponse) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *OpenSessionResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *OpenSessionResponse) GetServerHost() string {
	if x != nil {
		return x.ServerHost
	}
	return ""
}

func (x *OpenSessionResponse) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *OpenSessionResponse) GetStreamIds() []uint32 {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

func (x *OpenSessionResponse) GetMtuHint() uint32 {
	if x != nil {
		return x.MtuHint
	}
	return 0
}

func (x *OpenSessionResponse) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *OpenSessionResponse) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_grover_udp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{2}
}

func (x *CloseSessionRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_grover_udp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{3}
}

func (x *CloseSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateUdpPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortCount     uint32                 `protobuf:"varint,1,opt,name=port_count,json=portCount,proto3" json:"port_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUdpPortsRequest) Reset() {
	*x = CreateUdpPortsRequest{}
	mi := &file_grover_udp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUdpPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUdpPortsRequest) ProtoMessage() {}

func (x *CreateUdpPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUdpPortsRequest.ProtoReflect.Descriptor instead.
func (*CreateUdpPortsRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUdpPortsRequest) GetPortCount() uint32 {
	if x != nil {
		return x.PortCount
	}
	return 0
}

type CreateUdpPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []uint32               `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUdpPortsResponse) Reset() {
	*x = CreateUdpPortsResponse{}
	mi := &file_grover_udp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUdpPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUdpPortsResponse) ProtoMessage() {}

func (x *CreateUdpPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUdpPortsResponse.ProtoReflect.Descriptor instead.
func (*CreateUdpPortsResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUdpPortsResponse) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type DeleteUdpPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortNum       []uint32               `protobuf:"varint,1,rep,packed,name=port_num,json=portNum,proto3" json:"port_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUdpPortsRequest) Reset() {
	*x = DeleteUdpPortsRequest{}
	mi := &file_grover_udp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUdpPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUdpPortsRequest) ProtoMessage() {}

func (x *DeleteUdpPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUdpPortsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUdpPortsRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUdpPortsRequest) GetPortNum() []uint32 {
	if x != nil {
		return x.PortNum
	}
	return nil
}

type DeleteUdpPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUdpPortsResponse) Reset() {
	*x = DeleteUdpPortsResponse{}
	mi := &file_grover_udp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUdpPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUdpPortsResponse) ProtoMessage() {}

func (x *DeleteUdpPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUdpPortsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUdpPortsResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUdpPortsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortRequest) Reset() {
	*x = ListPortRequest{}
	mi := &file_grover_udp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortRequest) ProtoMessage() {}

func (x *ListPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortRequest.ProtoReflect.Descriptor instead.
func (*ListPortRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{8}
}

type ListPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          []uint32               `protobuf:"varint,1,rep,packed,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortResponse) Reset() {
	*x = ListPortResponse{}
	mi := &file_grover_udp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortResponse) ProtoMessage() {}

func (x *ListPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortResponse.ProtoReflect.Descriptor instead.
func (*ListPortResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{9}
}

func (x *ListPortResponse) GetPort() []uint32 {
	if x != nil {
		return x.Port
	}
	return nil
}

type StartServerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UdpPort        uint32                 `protobuf:"varint,1,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	WorkersPerFile uint32                 `protobuf:"varint,2,opt,name=workers_per_file,json=workersPerFile,proto3" json:"workers_per_file,omitempty"`
	MaxTransfers   uint32                 `protobuf:"varint,3,opt,name=max_transfers,json=maxTransfers,proto3" json:"max_transfers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartServerRequest) Reset() {
	*x = StartServerRequest{}
	mi := &file_grover_udp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerRequest) ProtoMessage() {}

func (x *StartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerRequest.ProtoReflect.Descriptor instead.
func (*StartServerRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{10}
}

func (x *StartServerRequest) GetUdpPort() uint32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

func (x *StartServerRequest) GetWorkersPerFile() uint32 {
	if x != nil {
		return x.WorkersPerFile
	}
	return 0
}

func (x *StartServerRequest) GetMaxTransfers() uint32 {
	if x != nil {
		return x.MaxTransfers
	}
	return 0
}

type StartServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerResponse) Reset() {
	*x = StartServerResponse{}
	mi := &file_grover_udp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerResponse) ProtoMessage() {}

func (x *StartServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerResponse.ProtoReflect.Descriptor instead.
func (*StartServerResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{11}
}

func (x *StartServerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartServerResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServerRequest) Reset() {
	*x = StopServerRequest{}
	mi := &file_grover_udp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerRequest) ProtoMessage() {}

func (x *StopServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServerRequest.ProtoReflect.Descriptor instead.
func (*StopServerRequest) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{12}
}

type StopServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServerResponse) Reset() {
	*x = StopServerResponse{}
	mi := &file_grover_udp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerResponse) ProtoMessage() {}

func (x *StopServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_udp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServerResponse.ProtoReflect.Descriptor instead.
func (*StopServerResponse) Descriptor() ([]byte, []int) {
	return file_grover_udp_proto_rawDescGZIP(), []int{13}
}

func (x *StopServerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StopServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grover_udp_proto protoreflect.FileDescriptor

const file_grover_udp_proto_rawDesc = "" +
	"\n" +
	"\x10grover_udp.proto\x12\fgroverudp.v1\"\xfe\x01\n" +
	"\x12OpenSessionRequest\x129\n" +
	"\x04mode\x18\x01 \x01(\x0e2%.groverudp.v1.OpenSessionRequest.ModeR\x04mode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12'\n" +
	"\x0fverify_checksum\x18\x04 \x01(\bR\x0everifyChecksum\x12)\n" +
	"\x10parallel_streams\x18\x05 \x01(\rR\x0fparallelStreams\"1\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04READ\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x02\"\x86\x02\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12\x1f\n" +
	"\vserver_host\x18\x03 \x01(\tR\n" +
	"serverHost\x12\x1f\n" +
	"\vserver_port\x18\x04 \x01(\rR\n" +
	"serverPort\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x05 \x03(\rR\tstreamIds\x12\x19\n" +
	"\bmtu_hint\x18\x06 \x01(\rR\amtuHint\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x04R\ttotalSize\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\rR\n" +
	"ttlSeconds\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\"&\n" +
	"\x14CloseSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"6\n" +
	"\x15CreateUdpPortsRequest\x12\x1d\n" +
	"\n" +
	"port_count\x18\x01 \x01(\rR\tportCount\".\n" +
	"\x16CreateUdpPortsResponse\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\rR\x05ports\"2\n" +
	"\x15DeleteUdpPortsRequest\x12\x19\n" +
	"\bport_num\x18\x01 \x03(\rR\aportNum\"(\n" +
	"\x16DeleteUdpPortsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x11\n" +
	"\x0fListPortRequest\"&\n" +
	"\x10ListPortResponse\x12\x12\n" +
	"\x04port\x18\x01 \x03(\rR\x04port\"~\n" +
	"\x12StartServerRequest\x12\x19\n" +
	"\budp_port\x18\x01 \x01(\rR\audpPort\x12(\n" +
	"\x10workers_per_file\x18\x02 \x01(\rR\x0eworkersPerFile\x12#\n" +
	"\rmax_transfers\x18\x03 \x01(\rR\fmaxTransfers\"S\n" +
	"\x13StartServerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11StopServerRequest\">\n" +
	"\x12StopServerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb9\x03\n" +
	"\fGroverServer\x12R\n" +
	"\vStartServer\x12 .groverudp.v1.StartServerRequest\x1a!.groverudp.v1.StartServerResponse\x12O\n" +
	"\n" +
	"StopServer\x12\x1f.groverudp.v1.StopServerRequest\x1a .groverudp.v1.StopServerResponse\x12J\n" +
	"\tListPorts\x12\x1d.groverudp.v1.ListPortRequest\x1a\x1e.groverudp.v1.ListPortResponse\x12[\n" +
	"\x0eDeleteUdpPorts\x12#.groverudp.v1.DeleteUdpPortsRequest\x1a$.groverudp.v1.DeleteUdpPortsResponse\x12[\n" +
	"\x0eCreateUdpPorts\x12#.groverudp.v1.CreateUdpPortsRequest\x1a$.groverudp.v1.CreateUdpPortsResponse2\xbc\x01\n" +
	"\x0fTransferControl\x12R\n" +
	"\vOpenSession\x12 .groverudp.v1.OpenSessionRequest\x1a!.groverudp.v1.OpenSessionResponse\x12U\n" +
	"\fCloseSession\x12!.groverudp.v1.CloseSessionRequest\x1a\".groverudp.v1.CloseSessionResponseBBZ@github.com/jgoldverg/grover/pkg/groverpb/groverudpv1;groverudpv1b\x06proto3"

var (
	file_grover_udp_proto_rawDescOnce sync.Once
	file_grover_udp_proto_rawDescData []byte
)

func file_grover_udp_proto_rawDescGZIP() []byte {
	file_grover_udp_proto_rawDescOnce.Do(func() {
		file_grover_udp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grover_udp_proto_rawDesc), len(file_grover_udp_proto_rawDesc)))
	})
	return file_grover_udp_proto_rawDescData
}

var file_grover_udp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grover_udp_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grover_udp_proto_goTypes = []any{
	(OpenSessionRequest_Mode)(0),   // 0: groverudp.v1.OpenSessionRequest.Mode
	(*OpenSessionRequest)(nil),     // 1: groverudp.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),    // 2: groverudp.v1.OpenSessionResponse
	(*CloseSessionRequest)(nil),    // 3: groverudp.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),   // 4: groverudp.v1.CloseSessionResponse
	(*CreateUdpPortsRequest)(nil),  // 5: groverudp.v1.CreateUdpPortsRequest
	(*CreateUdpPortsResponse)(nil), // 6: groverudp.v1.CreateUdpPortsResponse
	(*DeleteUdpPortsRequest)(nil),  // 7: groverudp.v1.DeleteUdpPortsRequest
	(*DeleteUdpPortsResponse)(nil), // 8: groverudp.v1.DeleteUdpPortsResponse
	(*ListPortRequest)(nil),        // 9: groverudp.v1.ListPortRequest
	(*ListPortResponse)(nil),       // 10: groverudp.v1.ListPortResponse
	(*StartServerRequest)(nil),     // 11: groverudp.v1.StartServerRequest
	(*StartServerResponse)(nil),    // 12: groverudp.v1.StartServerResponse
	(*StopServerRequest)(nil),      // 13: groverudp.v1.StopServerRequest
	(*StopServerResponse)(nil),     // 14: groverudp.v1.StopServerResponse
}
var file_grover_udp_proto_depIdxs = []int32{
	0,  // 0: groverudp.v1.OpenSessionRequest.mode:type_name -> groverudp.v1.OpenSessionRequest.Mode
	11, // 1: groverudp.v1.GroverServer.StartServer:input_type -> groverudp.v1.StartServerRequest
	13, // 2: groverudp.v1.GroverServer.StopServer:input_type -> groverudp.v1.StopServerRequest
	9,  // 3: groverudp.v1.GroverServer.ListPorts:input_type -> groverudp.v1.ListPortRequest
	7,  // 4: groverudp.v1.GroverServer.DeleteUdpPorts:input_type -> groverudp.v1.DeleteUdpPortsRequest
	5,  // 5: groverudp.v1.GroverServer.CreateUdpPorts:input_type -> groverudp.v1.CreateUdpPortsRequest
	1,  // 6: groverudp.v1.TransferControl.OpenSession:input_type -> groverudp.v1.OpenSessionRequest
	3,  // 7: groverudp.v1.TransferControl.CloseSession:input_type -> groverudp.v1.CloseSessionRequest
	12, // 8: groverudp.v1.GroverServer.StartServer:output_type -> groverudp.v1.StartServerResponse
	14, // 9: groverudp.v1.GroverServer.StopServer:output_type -> groverudp.v1.StopServerResponse
	10, // 10: groverudp.v1.GroverServer.ListPorts:output_type -> groverudp.v1.ListPortResponse
	8,  // 11: groverudp.v1.GroverServer.DeleteUdpPorts:output_type -> groverudp.v1.DeleteUdpPortsResponse
	6,  // 12: groverudp.v1.GroverServer.CreateUdpPorts:output_type -> groverudp.v1.CreateUdpPortsResponse
	2,  // 13: groverudp.v1.TransferControl.OpenSession:output_type -> groverudp.v1.OpenSessionResponse
	4,  // 14: groverudp.v1.TransferControl.CloseSession:output_type -> groverudp.v1.CloseSessionResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_grover_udp_proto_init() }
func file_grover_udp_proto_init() {
	if File_grover_udp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grover_udp_proto_rawDesc), len(file_grover_udp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grover_udp_proto_goTypes,
		DependencyIndexes: file_grover_udp_proto_depIdxs,
		EnumInfos:         file_grover_udp_proto_enumTypes,
		MessageInfos:      file_grover_udp_proto_msgTypes,
	}.Build()
	File_grover_udp_proto = out.File
	file_grover_udp_proto_goTypes = nil
	file_grover_udp_proto_depIdxs = nil
}
