// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grover.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointType int32

const (
	EndpointType_ENDPOINT_TYPE_UNSPECIFIED EndpointType = 0 // default value, must be 0
	EndpointType_HTTP                      EndpointType = 1
	EndpointType_LOCAL_FS                  EndpointType = 2
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "ENDPOINT_TYPE_UNSPECIFIED",
		1: "HTTP",
		2: "LOCAL_FS",
	}
	EndpointType_value = map[string]int32{
		"ENDPOINT_TYPE_UNSPECIFIED": 0,
		"HTTP":                      1,
		"LOCAL_FS":                  2,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_grover_proto_enumTypes[0].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_grover_proto_enumTypes[0]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{0}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_grover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.EndpointType" json:"type,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to CredentialIdentifier:
	//
	//	*ListFilesRequest_CredentialName
	//	*ListFilesRequest_CredentialUUID
	CredentialIdentifier isListFilesRequest_CredentialIdentifier `protobuf_oneof:"credential_identifier"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_grover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetCredentialIdentifier() isListFilesRequest_CredentialIdentifier {
	if x != nil {
		return x.CredentialIdentifier
	}
	return nil
}

func (x *ListFilesRequest) GetCredentialName() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*ListFilesRequest_CredentialName); ok {
			return x.CredentialName
		}
	}
	return ""
}

func (x *ListFilesRequest) GetCredentialUUID() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*ListFilesRequest_CredentialUUID); ok {
			return x.CredentialUUID
		}
	}
	return ""
}

type isListFilesRequest_CredentialIdentifier interface {
	isListFilesRequest_CredentialIdentifier()
}

type ListFilesRequest_CredentialName struct {
	CredentialName string `protobuf:"bytes,3,opt,name=credentialName,proto3,oneof"`
}

type ListFilesRequest_CredentialUUID struct {
	CredentialUUID string `protobuf:"bytes,4,opt,name=credentialUUID,proto3,oneof"`
}

func (*ListFilesRequest_CredentialName) isListFilesRequest_CredentialIdentifier() {}

func (*ListFilesRequest_CredentialUUID) isListFilesRequest_CredentialIdentifier() {}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_grover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{2}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type RemoveFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.EndpointType" json:"type,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to CredentialIdentifier:
	//
	//	*RemoveFileRequest_CredentialName
	//	*RemoveFileRequest_CredentialUUID
	CredentialIdentifier isRemoveFileRequest_CredentialIdentifier `protobuf_oneof:"credential_identifier"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_grover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFileRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *RemoveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveFileRequest) GetCredentialIdentifier() isRemoveFileRequest_CredentialIdentifier {
	if x != nil {
		return x.CredentialIdentifier
	}
	return nil
}

func (x *RemoveFileRequest) GetCredentialName() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*RemoveFileRequest_CredentialName); ok {
			return x.CredentialName
		}
	}
	return ""
}

func (x *RemoveFileRequest) GetCredentialUUID() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*RemoveFileRequest_CredentialUUID); ok {
			return x.CredentialUUID
		}
	}
	return ""
}

type isRemoveFileRequest_CredentialIdentifier interface {
	isRemoveFileRequest_CredentialIdentifier()
}

type RemoveFileRequest_CredentialName struct {
	CredentialName string `protobuf:"bytes,3,opt,name=credentialName,proto3,oneof"`
}

type RemoveFileRequest_CredentialUUID struct {
	CredentialUUID string `protobuf:"bytes,4,opt,name=credentialUUID,proto3,oneof"`
}

func (*RemoveFileRequest_CredentialName) isRemoveFileRequest_CredentialIdentifier() {}

func (*RemoveFileRequest_CredentialUUID) isRemoveFileRequest_CredentialIdentifier() {}

type RemoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileResponse) Reset() {
	*x = RemoveFileResponse{}
	mi := &file_grover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResponse) ProtoMessage() {}

func (x *RemoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_grover_proto protoreflect.FileDescriptor

const file_grover_proto_rawDesc = "" +
	"\n" +
	"\fgrover.proto\x12\x06grover\"B\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\xbd\x01\n" +
	"\x10ListFilesRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.grover.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12(\n" +
	"\x0ecredentialName\x18\x03 \x01(\tH\x00R\x0ecredentialName\x12(\n" +
	"\x0ecredentialUUID\x18\x04 \x01(\tH\x00R\x0ecredentialUUIDB\x17\n" +
	"\x15credential_identifier\";\n" +
	"\x11ListFilesResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.grover.FileInfoR\x05files\"\xbe\x01\n" +
	"\x11RemoveFileRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.grover.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12(\n" +
	"\x0ecredentialName\x18\x03 \x01(\tH\x00R\x0ecredentialName\x12(\n" +
	"\x0ecredentialUUID\x18\x04 \x01(\tH\x00R\x0ecredentialUUIDB\x17\n" +
	"\x15credential_identifier\".\n" +
	"\x12RemoveFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*E\n" +
	"\fEndpointType\x12\x1d\n" +
	"\x19ENDPOINT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\f\n" +
	"\bLOCAL_FS\x10\x022\x8b\x01\n" +
	"\vFileService\x12;\n" +
	"\x04List\x12\x18.grover.ListFilesRequest\x1a\x19.grover.ListFilesResponse\x12?\n" +
	"\x06Remove\x12\x19.grover.RemoveFileRequest\x1a\x1a.grover.RemoveFileResponseB#Z!github.com/jgoldverg/grover/pb;pbb\x06proto3"

var (
	file_grover_proto_rawDescOnce sync.Once
	file_grover_proto_rawDescData []byte
)

func file_grover_proto_rawDescGZIP() []byte {
	file_grover_proto_rawDescOnce.Do(func() {
		file_grover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grover_proto_rawDesc), len(file_grover_proto_rawDesc)))
	})
	return file_grover_proto_rawDescData
}

var file_grover_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grover_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grover_proto_goTypes = []any{
	(EndpointType)(0),          // 0: grover.EndpointType
	(*FileInfo)(nil),           // 1: grover.FileInfo
	(*ListFilesRequest)(nil),   // 2: grover.ListFilesRequest
	(*ListFilesResponse)(nil),  // 3: grover.ListFilesResponse
	(*RemoveFileRequest)(nil),  // 4: grover.RemoveFileRequest
	(*RemoveFileResponse)(nil), // 5: grover.RemoveFileResponse
}
var file_grover_proto_depIdxs = []int32{
	0, // 0: grover.ListFilesRequest.type:type_name -> grover.EndpointType
	1, // 1: grover.ListFilesResponse.files:type_name -> grover.FileInfo
	0, // 2: grover.RemoveFileRequest.type:type_name -> grover.EndpointType
	2, // 3: grover.FileService.List:input_type -> grover.ListFilesRequest
	4, // 4: grover.FileService.Remove:input_type -> grover.RemoveFileRequest
	3, // 5: grover.FileService.List:output_type -> grover.ListFilesResponse
	5, // 6: grover.FileService.Remove:output_type -> grover.RemoveFileResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grover_proto_init() }
func file_grover_proto_init() {
	if File_grover_proto != nil {
		return
	}
	file_grover_proto_msgTypes[1].OneofWrappers = []any{
		(*ListFilesRequest_CredentialName)(nil),
		(*ListFilesRequest_CredentialUUID)(nil),
	}
	file_grover_proto_msgTypes[3].OneofWrappers = []any{
		(*RemoveFileRequest_CredentialName)(nil),
		(*RemoveFileRequest_CredentialUUID)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grover_proto_rawDesc), len(file_grover_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grover_proto_goTypes,
		DependencyIndexes: file_grover_proto_depIdxs,
		EnumInfos:         file_grover_proto_enumTypes,
		MessageInfos:      file_grover_proto_msgTypes,
	}.Build()
	File_grover_proto = out.File
	file_grover_proto_goTypes = nil
	file_grover_proto_depIdxs = nil
}
