// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: grover.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointType int32

const (
	EndpointType_ENDPOINT_TYPE_UNSPECIFIED EndpointType = 0 // default value, must be 0
	EndpointType_HTTP                      EndpointType = 1
	EndpointType_LOCAL_FS                  EndpointType = 2
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "ENDPOINT_TYPE_UNSPECIFIED",
		1: "HTTP",
		2: "LOCAL_FS",
	}
	EndpointType_value = map[string]int32{
		"ENDPOINT_TYPE_UNSPECIFIED": 0,
		"HTTP":                      1,
		"LOCAL_FS":                  2,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_grover_proto_enumTypes[0].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_grover_proto_enumTypes[0]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{0}
}

type CredentialType int32

const (
	CredentialType_CREDENTIAL_TYPE_UNSPECIFIED CredentialType = 0
	CredentialType_SSH_CREDENTIAL_TYPE         CredentialType = 1
	CredentialType_BASIC_CREDENTIAL_TYPE       CredentialType = 2
)

// Enum value maps for CredentialType.
var (
	CredentialType_name = map[int32]string{
		0: "CREDENTIAL_TYPE_UNSPECIFIED",
		1: "SSH_CREDENTIAL_TYPE",
		2: "BASIC_CREDENTIAL_TYPE",
	}
	CredentialType_value = map[string]int32{
		"CREDENTIAL_TYPE_UNSPECIFIED": 0,
		"SSH_CREDENTIAL_TYPE":         1,
		"BASIC_CREDENTIAL_TYPE":       2,
	}
)

func (x CredentialType) Enum() *CredentialType {
	p := new(CredentialType)
	*p = x
	return p
}

func (x CredentialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialType) Descriptor() protoreflect.EnumDescriptor {
	return file_grover_proto_enumTypes[1].Descriptor()
}

func (CredentialType) Type() protoreflect.EnumType {
	return &file_grover_proto_enumTypes[1]
}

func (x CredentialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialType.Descriptor instead.
func (CredentialType) EnumDescriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{1}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_grover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.EndpointType" json:"type,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to CredentialIdentifier:
	//
	//	*ListFilesRequest_CredentialName
	//	*ListFilesRequest_CredentialUUID
	CredentialIdentifier isListFilesRequest_CredentialIdentifier `protobuf_oneof:"credential_identifier"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_grover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetCredentialIdentifier() isListFilesRequest_CredentialIdentifier {
	if x != nil {
		return x.CredentialIdentifier
	}
	return nil
}

func (x *ListFilesRequest) GetCredentialName() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*ListFilesRequest_CredentialName); ok {
			return x.CredentialName
		}
	}
	return ""
}

func (x *ListFilesRequest) GetCredentialUUID() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*ListFilesRequest_CredentialUUID); ok {
			return x.CredentialUUID
		}
	}
	return ""
}

type isListFilesRequest_CredentialIdentifier interface {
	isListFilesRequest_CredentialIdentifier()
}

type ListFilesRequest_CredentialName struct {
	CredentialName string `protobuf:"bytes,3,opt,name=credentialName,proto3,oneof"`
}

type ListFilesRequest_CredentialUUID struct {
	CredentialUUID string `protobuf:"bytes,4,opt,name=credentialUUID,proto3,oneof"`
}

func (*ListFilesRequest_CredentialName) isListFilesRequest_CredentialIdentifier() {}

func (*ListFilesRequest_CredentialUUID) isListFilesRequest_CredentialIdentifier() {}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_grover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{2}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type RemoveFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EndpointType           `protobuf:"varint,1,opt,name=type,proto3,enum=grover.EndpointType" json:"type,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to CredentialIdentifier:
	//
	//	*RemoveFileRequest_CredentialName
	//	*RemoveFileRequest_CredentialUUID
	CredentialIdentifier isRemoveFileRequest_CredentialIdentifier `protobuf_oneof:"credential_identifier"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_grover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFileRequest) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNSPECIFIED
}

func (x *RemoveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveFileRequest) GetCredentialIdentifier() isRemoveFileRequest_CredentialIdentifier {
	if x != nil {
		return x.CredentialIdentifier
	}
	return nil
}

func (x *RemoveFileRequest) GetCredentialName() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*RemoveFileRequest_CredentialName); ok {
			return x.CredentialName
		}
	}
	return ""
}

func (x *RemoveFileRequest) GetCredentialUUID() string {
	if x != nil {
		if x, ok := x.CredentialIdentifier.(*RemoveFileRequest_CredentialUUID); ok {
			return x.CredentialUUID
		}
	}
	return ""
}

type isRemoveFileRequest_CredentialIdentifier interface {
	isRemoveFileRequest_CredentialIdentifier()
}

type RemoveFileRequest_CredentialName struct {
	CredentialName string `protobuf:"bytes,3,opt,name=credentialName,proto3,oneof"`
}

type RemoveFileRequest_CredentialUUID struct {
	CredentialUUID string `protobuf:"bytes,4,opt,name=credentialUUID,proto3,oneof"`
}

func (*RemoveFileRequest_CredentialName) isRemoveFileRequest_CredentialIdentifier() {}

func (*RemoveFileRequest_CredentialUUID) isRemoveFileRequest_CredentialIdentifier() {}

type RemoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileResponse) Reset() {
	*x = RemoveFileResponse{}
	mi := &file_grover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResponse) ProtoMessage() {}

func (x *RemoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Selector used in requests (UUID or name).
type CredentialRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*CredentialRef_CredentialUuid
	//	*CredentialRef_CredentialName
	Ref           isCredentialRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRef) Reset() {
	*x = CredentialRef{}
	mi := &file_grover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRef) ProtoMessage() {}

func (x *CredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRef.ProtoReflect.Descriptor instead.
func (*CredentialRef) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialRef) GetRef() isCredentialRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *CredentialRef) GetCredentialUuid() string {
	if x != nil {
		if x, ok := x.Ref.(*CredentialRef_CredentialUuid); ok {
			return x.CredentialUuid
		}
	}
	return ""
}

func (x *CredentialRef) GetCredentialName() string {
	if x != nil {
		if x, ok := x.Ref.(*CredentialRef_CredentialName); ok {
			return x.CredentialName
		}
	}
	return ""
}

type isCredentialRef_Ref interface {
	isCredentialRef_Ref()
}

type CredentialRef_CredentialUuid struct {
	CredentialUuid string `protobuf:"bytes,1,opt,name=credential_uuid,json=credentialUuid,proto3,oneof"`
}

type CredentialRef_CredentialName struct {
	CredentialName string `protobuf:"bytes,2,opt,name=credential_name,json=credentialName,proto3,oneof"`
}

func (*CredentialRef_CredentialUuid) isCredentialRef_Ref() {}

func (*CredentialRef_CredentialName) isCredentialRef_Ref() {}

// Full credential (includes secrets by design).
type Credential struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialUuid string                 `protobuf:"bytes,1,opt,name=credential_uuid,json=credentialUuid,proto3" json:"credential_uuid,omitempty"` // SSHCredential.UUID / BasicAuthCredential.UUID
	CredentialName string                 `protobuf:"bytes,2,opt,name=credential_name,json=credentialName,proto3" json:"credential_name,omitempty"` // .Name
	Type           CredentialType         `protobuf:"varint,3,opt,name=type,proto3,enum=grover.CredentialType" json:"type,omitempty"`               // "ssh"/"basic" -> enum below
	// Types that are valid to be assigned to Details:
	//
	//	*Credential_Basic
	//	*Credential_Ssh
	Details       isCredential_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_grover_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{6}
}

func (x *Credential) GetCredentialUuid() string {
	if x != nil {
		return x.CredentialUuid
	}
	return ""
}

func (x *Credential) GetCredentialName() string {
	if x != nil {
		return x.CredentialName
	}
	return ""
}

func (x *Credential) GetType() CredentialType {
	if x != nil {
		return x.Type
	}
	return CredentialType_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *Credential) GetDetails() isCredential_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Credential) GetBasic() *BasicDetails {
	if x != nil {
		if x, ok := x.Details.(*Credential_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *Credential) GetSsh() *SshDetails {
	if x != nil {
		if x, ok := x.Details.(*Credential_Ssh); ok {
			return x.Ssh
		}
	}
	return nil
}

type isCredential_Details interface {
	isCredential_Details()
}

type Credential_Basic struct {
	Basic *BasicDetails `protobuf:"bytes,10,opt,name=basic,proto3,oneof"` // for BASIC
}

type Credential_Ssh struct {
	Ssh *SshDetails `protobuf:"bytes,11,opt,name=ssh,proto3,oneof"` // for SSH
}

func (*Credential_Basic) isCredential_Details() {}

func (*Credential_Ssh) isCredential_Details() {}

type BasicDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // BasicAuthCredential.Username
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // BasicAuthCredential.Password  (secret)
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`           // BasicAuthCredential.URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicDetails) Reset() {
	*x = BasicDetails{}
	mi := &file_grover_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicDetails) ProtoMessage() {}

func (x *BasicDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicDetails.ProtoReflect.Descriptor instead.
func (*BasicDetails) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{7}
}

func (x *BasicDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BasicDetails) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SshDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	UseAgent      bool                   `protobuf:"varint,6,opt,name=use_agent,json=useAgent,proto3" json:"use_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshDetails) Reset() {
	*x = SshDetails{}
	mi := &file_grover_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshDetails) ProtoMessage() {}

func (x *SshDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshDetails.ProtoReflect.Descriptor instead.
func (*SshDetails) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{8}
}

func (x *SshDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SshDetails) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SshDetails) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SshDetails) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SshDetails) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SshDetails) GetUseAgent() bool {
	if x != nil {
		return x.UseAgent
	}
	return false
}

type CreateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialRequest) Reset() {
	*x = CreateCredentialRequest{}
	mi := &file_grover_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialRequest) ProtoMessage() {}

func (x *CreateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCredentialRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type CreateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialResponse) Reset() {
	*x = CreateCredentialResponse{}
	mi := &file_grover_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialResponse) ProtoMessage() {}

func (x *CreateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialResponse.ProtoReflect.Descriptor instead.
func (*CreateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{10}
}

type GetCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *CredentialRef         `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_grover_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{11}
}

func (x *GetCredentialRequest) GetRef() *CredentialRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_grover_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{12}
}

func (x *GetCredentialResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type ListCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CredentialType         `protobuf:"varint,1,opt,name=type,proto3,enum=grover.CredentialType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsRequest) Reset() {
	*x = ListCredentialsRequest{}
	mi := &file_grover_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsRequest) ProtoMessage() {}

func (x *ListCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{13}
}

func (x *ListCredentialsRequest) GetType() CredentialType {
	if x != nil {
		return x.Type
	}
	return CredentialType_CREDENTIAL_TYPE_UNSPECIFIED
}

type ListCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*Credential          `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsResponse) Reset() {
	*x = ListCredentialsResponse{}
	mi := &file_grover_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsResponse) ProtoMessage() {}

func (x *ListCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{14}
}

func (x *ListCredentialsResponse) GetCredentials() []*Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ListCredentialsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *CredentialRef         `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_grover_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCredentialRequest) GetRef() *CredentialRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_grover_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grover_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_grover_proto_rawDescGZIP(), []int{16}
}

var File_grover_proto protoreflect.FileDescriptor

const file_grover_proto_rawDesc = "" +
	"\n" +
	"\fgrover.proto\x12\x06grover\"B\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\xbd\x01\n" +
	"\x10ListFilesRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.grover.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12(\n" +
	"\x0ecredentialName\x18\x03 \x01(\tH\x00R\x0ecredentialName\x12(\n" +
	"\x0ecredentialUUID\x18\x04 \x01(\tH\x00R\x0ecredentialUUIDB\x17\n" +
	"\x15credential_identifier\";\n" +
	"\x11ListFilesResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.grover.FileInfoR\x05files\"\xbe\x01\n" +
	"\x11RemoveFileRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.grover.EndpointTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12(\n" +
	"\x0ecredentialName\x18\x03 \x01(\tH\x00R\x0ecredentialName\x12(\n" +
	"\x0ecredentialUUID\x18\x04 \x01(\tH\x00R\x0ecredentialUUIDB\x17\n" +
	"\x15credential_identifier\".\n" +
	"\x12RemoveFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\rCredentialRef\x12)\n" +
	"\x0fcredential_uuid\x18\x01 \x01(\tH\x00R\x0ecredentialUuid\x12)\n" +
	"\x0fcredential_name\x18\x02 \x01(\tH\x00R\x0ecredentialNameB\x05\n" +
	"\x03ref\"\xeb\x01\n" +
	"\n" +
	"Credential\x12'\n" +
	"\x0fcredential_uuid\x18\x01 \x01(\tR\x0ecredentialUuid\x12'\n" +
	"\x0fcredential_name\x18\x02 \x01(\tR\x0ecredentialName\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.grover.CredentialTypeR\x04type\x12,\n" +
	"\x05basic\x18\n" +
	" \x01(\v2\x14.grover.BasicDetailsH\x00R\x05basic\x12&\n" +
	"\x03ssh\x18\v \x01(\v2\x12.grover.SshDetailsH\x00R\x03sshB\t\n" +
	"\adetails\"X\n" +
	"\fBasicDetails\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xad\x01\n" +
	"\n" +
	"SshDetails\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\x12\x1b\n" +
	"\tuse_agent\x18\x06 \x01(\bR\buseAgent\"M\n" +
	"\x17CreateCredentialRequest\x122\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x12.grover.CredentialR\n" +
	"credential\"\x1a\n" +
	"\x18CreateCredentialResponse\"?\n" +
	"\x14GetCredentialRequest\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.grover.CredentialRefR\x03ref\"K\n" +
	"\x15GetCredentialResponse\x122\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x12.grover.CredentialR\n" +
	"credential\"D\n" +
	"\x16ListCredentialsRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.grover.CredentialTypeR\x04type\"w\n" +
	"\x17ListCredentialsResponse\x124\n" +
	"\vcredentials\x18\x01 \x03(\v2\x12.grover.CredentialR\vcredentials\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x17DeleteCredentialRequest\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.grover.CredentialRefR\x03ref\"\x1a\n" +
	"\x18DeleteCredentialResponse*E\n" +
	"\fEndpointType\x12\x1d\n" +
	"\x19ENDPOINT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\f\n" +
	"\bLOCAL_FS\x10\x02*e\n" +
	"\x0eCredentialType\x12\x1f\n" +
	"\x1bCREDENTIAL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SSH_CREDENTIAL_TYPE\x10\x01\x12\x19\n" +
	"\x15BASIC_CREDENTIAL_TYPE\x10\x022\x8b\x01\n" +
	"\vFileService\x12;\n" +
	"\x04List\x12\x18.grover.ListFilesRequest\x1a\x19.grover.ListFilesResponse\x12?\n" +
	"\x06Remove\x12\x19.grover.RemoveFileRequest\x1a\x1a.grover.RemoveFileResponse2\xba\x02\n" +
	"\x11CredentialService\x12K\n" +
	"\x06Create\x12\x1f.grover.CreateCredentialRequest\x1a .grover.CreateCredentialResponse\x12B\n" +
	"\x03Get\x12\x1c.grover.GetCredentialRequest\x1a\x1d.grover.GetCredentialResponse\x12G\n" +
	"\x04List\x12\x1e.grover.ListCredentialsRequest\x1a\x1f.grover.ListCredentialsResponse\x12K\n" +
	"\x06Delete\x12\x1f.grover.DeleteCredentialRequest\x1a .grover.DeleteCredentialResponseB#Z!github.com/jgoldverg/grover/pb;pbb\x06proto3"

var (
	file_grover_proto_rawDescOnce sync.Once
	file_grover_proto_rawDescData []byte
)

func file_grover_proto_rawDescGZIP() []byte {
	file_grover_proto_rawDescOnce.Do(func() {
		file_grover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grover_proto_rawDesc), len(file_grover_proto_rawDesc)))
	})
	return file_grover_proto_rawDescData
}

var file_grover_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grover_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_grover_proto_goTypes = []any{
	(EndpointType)(0),                // 0: grover.EndpointType
	(CredentialType)(0),              // 1: grover.CredentialType
	(*FileInfo)(nil),                 // 2: grover.FileInfo
	(*ListFilesRequest)(nil),         // 3: grover.ListFilesRequest
	(*ListFilesResponse)(nil),        // 4: grover.ListFilesResponse
	(*RemoveFileRequest)(nil),        // 5: grover.RemoveFileRequest
	(*RemoveFileResponse)(nil),       // 6: grover.RemoveFileResponse
	(*CredentialRef)(nil),            // 7: grover.CredentialRef
	(*Credential)(nil),               // 8: grover.Credential
	(*BasicDetails)(nil),             // 9: grover.BasicDetails
	(*SshDetails)(nil),               // 10: grover.SshDetails
	(*CreateCredentialRequest)(nil),  // 11: grover.CreateCredentialRequest
	(*CreateCredentialResponse)(nil), // 12: grover.CreateCredentialResponse
	(*GetCredentialRequest)(nil),     // 13: grover.GetCredentialRequest
	(*GetCredentialResponse)(nil),    // 14: grover.GetCredentialResponse
	(*ListCredentialsRequest)(nil),   // 15: grover.ListCredentialsRequest
	(*ListCredentialsResponse)(nil),  // 16: grover.ListCredentialsResponse
	(*DeleteCredentialRequest)(nil),  // 17: grover.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil), // 18: grover.DeleteCredentialResponse
}
var file_grover_proto_depIdxs = []int32{
	0,  // 0: grover.ListFilesRequest.type:type_name -> grover.EndpointType
	2,  // 1: grover.ListFilesResponse.files:type_name -> grover.FileInfo
	0,  // 2: grover.RemoveFileRequest.type:type_name -> grover.EndpointType
	1,  // 3: grover.Credential.type:type_name -> grover.CredentialType
	9,  // 4: grover.Credential.basic:type_name -> grover.BasicDetails
	10, // 5: grover.Credential.ssh:type_name -> grover.SshDetails
	8,  // 6: grover.CreateCredentialRequest.credential:type_name -> grover.Credential
	7,  // 7: grover.GetCredentialRequest.ref:type_name -> grover.CredentialRef
	8,  // 8: grover.GetCredentialResponse.credential:type_name -> grover.Credential
	1,  // 9: grover.ListCredentialsRequest.type:type_name -> grover.CredentialType
	8,  // 10: grover.ListCredentialsResponse.credentials:type_name -> grover.Credential
	7,  // 11: grover.DeleteCredentialRequest.ref:type_name -> grover.CredentialRef
	3,  // 12: grover.FileService.List:input_type -> grover.ListFilesRequest
	5,  // 13: grover.FileService.Remove:input_type -> grover.RemoveFileRequest
	11, // 14: grover.CredentialService.Create:input_type -> grover.CreateCredentialRequest
	13, // 15: grover.CredentialService.Get:input_type -> grover.GetCredentialRequest
	15, // 16: grover.CredentialService.List:input_type -> grover.ListCredentialsRequest
	17, // 17: grover.CredentialService.Delete:input_type -> grover.DeleteCredentialRequest
	4,  // 18: grover.FileService.List:output_type -> grover.ListFilesResponse
	6,  // 19: grover.FileService.Remove:output_type -> grover.RemoveFileResponse
	12, // 20: grover.CredentialService.Create:output_type -> grover.CreateCredentialResponse
	14, // 21: grover.CredentialService.Get:output_type -> grover.GetCredentialResponse
	16, // 22: grover.CredentialService.List:output_type -> grover.ListCredentialsResponse
	18, // 23: grover.CredentialService.Delete:output_type -> grover.DeleteCredentialResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_grover_proto_init() }
func file_grover_proto_init() {
	if File_grover_proto != nil {
		return
	}
	file_grover_proto_msgTypes[1].OneofWrappers = []any{
		(*ListFilesRequest_CredentialName)(nil),
		(*ListFilesRequest_CredentialUUID)(nil),
	}
	file_grover_proto_msgTypes[3].OneofWrappers = []any{
		(*RemoveFileRequest_CredentialName)(nil),
		(*RemoveFileRequest_CredentialUUID)(nil),
	}
	file_grover_proto_msgTypes[5].OneofWrappers = []any{
		(*CredentialRef_CredentialUuid)(nil),
		(*CredentialRef_CredentialName)(nil),
	}
	file_grover_proto_msgTypes[6].OneofWrappers = []any{
		(*Credential_Basic)(nil),
		(*Credential_Ssh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grover_proto_rawDesc), len(file_grover_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grover_proto_goTypes,
		DependencyIndexes: file_grover_proto_depIdxs,
		EnumInfos:         file_grover_proto_enumTypes,
		MessageInfos:      file_grover_proto_msgTypes,
	}.Build()
	File_grover_proto = out.File
	file_grover_proto_goTypes = nil
	file_grover_proto_depIdxs = nil
}
